### ISSUE TITLE
Updating Nodes

### ISSUE THREAD

**Issue by AimanMRT** [croogo/croogo#1000]
Im just added new function inside controller for adding new model..when i login admin everything ok.. after i login with another role the new model cannot be reach..im checking if got any nodes for the new function that create..but it ddnt appear on croogo admin page..how to solve this issue..

**Comment by miketallroth** [comment]
First, are you blending the words "model" and "node" together? If not, please provide more detail about exactly what you're doing by creating new models, etc.

Otherwise, please check the node's published status; an unpublished node would not be visible to non-admin roles by default. And make sure you did not mistakenly add Access control on the node; a node with blank Access control is visible to all, but any entry there will be restricted to only that role.

**Comment by AimanMRT** [comment]
> First, are you blending the words "model" and "node" together? If not, please provide more detail about exactly what you're doing by creating new models, etc.
> 
> Otherwise, please check the node's published status; an unpublished node would not be visible to non-admin roles by default. And make sure you did not mistakenly add Access control on the node; a node with blank Access control is visible to all, but any entry there will be restricted to only that role.

Node published/unpublished not appear at admin template..how to syncronize it..use cake console or any way..admin can see it..if im login different acc it cant be operate..how to that node at admin page..to im allowing that node operate with another profile..not just admin..

**Comment by AimanMRT** [comment]
> First, are you blending the words "model" and "node" together? If not, please provide more detail about exactly what you're doing by creating new models, etc.
> 
> Otherwise, please check the node's published status; an unpublished node would not be visible to non-admin roles by default. And make sure you did not mistakenly add Access control on the node; a node with blank Access control is visible to all, but any entry there will be restricted to only that role.

Yeah..im creating new model..add_fa and add_td..and im inserting function add_fa and add_td at controller..

**Comment by miketallroth** [comment]
> Node published/unpublished not appear at admin template..how to syncronize it

What version of Croogo are you using? Published status has been a part of Croogo for many versions. If you do not see the option to publish a node, perhaps something went wrong in your installation.

**Comment by AimanMRT** [comment]
> > Node published/unpublished not appear at admin template..how to syncronize it
> 
> What version of Croogo are you using? Published status has been a part of Croogo for many versions. If you do not see the option to publish a node, perhaps something went wrong in your installation.

Croogo 2.*.*..the node insert before this all working normal..im juat create new model and added new function in controller..that new one ddnt appear at admin template there..
what u will do if just added new model and update controller added new function??

**Comment by AimanMRT** [comment]
Already done..need to acl_sync..plugin aclextras .
