### ISSUE TITLE
Tools plugin

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#239]
Created by **[fahad19](https://github.com/fahad19)**, 17th Feb 2010. _(originally [Lighthouse ticket #26](http://croogo.lighthouseapp.com/projects/32818/tickets/26))_:

---

Desired features
- Import/Export site (database)
- One click upgrade to latest version
- Enable/Disable caching
- Clear cache

**Comment by rchavik** [comment]
clearing cache already supported in core since 3.x.

Closing since I've no bandwith to do backup/upgrade
