### ISSUE TITLE
page hierarchy modification

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#247]
Created by **spooknick**, 27th Apr 2010. _(originally [Lighthouse ticket #77](http://croogo.lighthouseapp.com/projects/32818/tickets/77))_:

---

I would be nice to be able to change the page tree, not only by changing the parents but also rearranging the children one with another. And also to be able to display the tree in content list. The id doesn't  help I think.
I love croogo

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
