### ISSUE TITLE
Active Menu Highlighting

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#250]
Created by **Matt Trimarchi**, 29th May 2010. *(originally [Lighthouse ticket #100](http://croogo.lighthouseapp.com/projects/32818/tickets/100))*:
- - - -

The menu system should check the full path and add class="selected" if it is found.

For example:

/blog/term/announcements

should add the class="selected" to the menu item "blog"

**Comment by rchavik** [comment]
Closing since this is not valid anymore.
