### ISSUE TITLE
 Node Controller change

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#252]
Created by **theZiki**, 22nd Jun 2010. _(originally [Lighthouse ticket #110](http://croogo.lighthouseapp.com/projects/32818/tickets/110))_:

---

I had problem, how to attach some models on paginate from plugin hook,
so i made some changes to node controller.

First node controller beforeFilter function: http://bin.cakephp.org/view/897402459

Second node controller index,promoted, term, search actions I merged
array: http://bin.cakephp.org/view/1999880637

And this is in hook startup action: http://bin.cakephp.org/view/1108324185

So this is solution for plugins if we want to attach contain models
for pagination, maybe there is better solutions, I will use this for
me, until something else be offical.

**Comment by rchavik** [comment]
Customizing queries in >= 3.x should be easier since it uses cakephp 3.x orm
