### ISSUE TITLE
restrict default file editor path to uploads

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#264]
Created by **Lucian Sabo**, 12th Aug 2011. _(originally [Lighthouse ticket #198](http://croogo.lighthouseapp.com/projects/32818/tickets/198))_:

---

I don't think it is a good idea to let users access the web root with all sensible croogo and cake files.
So, I restricted opening the web root folder. I only allow the user to access the upload folder, which is enough for a common user.

I think a CMS should not allow content editors to modify it's core files.
Of couse the changes are only naive. The filemanager needs to protect itself from malicious users passing disallowed paths by GET. It is still a good protection for the legitimate users shooting their foot.
If you think this is worth adding I can modify the class to enforce security on disallowed paths.

Here are the changes in fliemanager_controller:

define a new private property:
private $_defaultPath;

in beforeFilter():
add:
$this->_defaultPath = WWW_ROOT . 'uploads';

in admin_browse():
change:

if (isset($this->params['url']['path'])) {
    $path = $this->params['url']['path'];
} else {
    $path = APP;
}

to:

if (isset($this->params['url']['path'])) {
    $path = $this->params['url']['path'];
} else {
    $path = $this->_defaultPath;
}

and change
$regex = '/^' . preg_quote(APP, '/') . '/';
to
$regex = '/^' . preg_quote($this->_defaultPath, '/') . '/';

**Comment by rchavik** [comment]
4.x restricts to webroot/assets
