### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#282]
Created by **[Rachman Chavik](https://github.com/rchavik)**, 26th Oct 2012. _(originally [Lighthouse ticket #330](http://croogo.lighthouseapp.com/projects/32818/tickets/330))_:

---

Offer RESTful API by core, to allow easy integration with third-party apps (could be an iPhone app too)

**Comment by Wouter0100** [comment]
If we could implement CRUD into Croogo, this issue is nearly done by CRUD.

**Comment by rchavik** [comment]
crud-json-api is now in > 4.0
