### ISSUE TITLE
Adding/removing front-end menu

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#303]
Created by **[Rachman Chavik](https://github.com/rchavik)**, 25th Aug 2013. _(originally [Lighthouse ticket #420](http://croogo.lighthouseapp.com/projects/32818/tickets/420))_:

---
- Some kind of API/utility to dynamically add/remove menu
- Or conditions/callback that can determine whether menu is visible or hidden

**Comment by rchavik** [comment]
From 3.x we can restrict via ACL
