### ISSUE TITLE
increase usability of tags

### ISSUE THREAD

**Issue by lh-import** [croogo/croogo#309]
Created by **dekna**, 27th Nov 2013. _(originally [Lighthouse ticket #458](http://croogo.lighthouseapp.com/projects/32818/tickets/458))_:

---

It would be nice to have the possibility create tags on the fly when creating an node.
There are a lot of good jquery/js libs to do this: http://stackoverflow.com/a/2674466

Regards,...

**Comment by rchavik** [comment]
Implemented as free tags option in >3.x
