### ISSUE TITLE
update jquery/ui

### ISSUE THREAD

**Issue by sakulstra** [croogo/croogo#367]
is there a reason, why crooco is still using jquery 1.7.2 an ui 1.8.18?
if not, i would recommend upgrading to the latest 1.x - there are huge speed improvements and especially in ui a lot of bugfixes.

I created a branch with my attempt: https://github.com/sakulstra/croogo/tree/js-dependencies
As far as i can see elastic isn't maintained any more - so it's probably no bad idea to drop it

edit: perhaps use composer to keep them updated http://stackoverflow.com/questions/11663559/how-to-install-jquery-with-composer ?

**Comment by rchavik** [comment]
Not relevant for > 3.x since many libs have been updated and some have removed
