### ISSUE TITLE
Selectbox multiselect in admin panel

### ISSUE THREAD

**Issue by sitex** [croogo/croogo#469]
It's very inconvenient to use Selectbox multiselect in current admin panel. See Access Tab user's roles selector. Checkboxes would a lot more ease and fun to use there.

**Comment by ionas** [comment]
A multi select box is very viable as it can handle a large number of multi select items in a very condense way.

I suggest to leave it as be and add a javascript that splits it in a top and bottom. Top being the whole list, bottom being the list of selected items. When you click on any top list icon, it will be moved to the bottom list (e.g. selected list). This should be possible with unobstrusive optional javascript (e.g. if you have js disabled, its just one multiple select box).
