### ISSUE TITLE
RFC: Deprecate/Remove use of Config/settings.json

### ISSUE THREAD

**Issue by rchavik** [croogo/croogo#484]
This file is basically a file cache, generated from values stored in the `settings` table.  We should try to investigate the impact of removing dependency on this file and store it in the cache instead.

**Comment by rchavik** [comment]
We should remove this and investigate a better mechanism.

See #642

**Comment by cdepre-sme** [comment]
settings.json has been removed in 3.0

**Comment by Wouter0100** [comment]
In 3.0 it's replaced with a database config, yeah.
