### ISSUE TITLE
Blocks - exclude fron certain pages

### ISSUE THREAD

**Issue by NetLancer** [croogo/croogo#592]
What if needed to exclude blocks from certain pages (e.g. index-page) and I don't know how many pages my site's going to have in future, listing 'Visibility Paths' for all blocks to include (in order to exclude from non-listed page) is going to turn somewhat too bulky. Is there a wise solution ?

**Comment by rchavik** [comment]
Turns out this is already raised in https://github.com/croogo/croogo/issues/241 and solved in https://github.com/croogo/croogo/pull/347
