### ISSUE TITLE
Croogo's for cakePHP technicians

### ISSUE THREAD

**Issue by NetLancer** [croogo/croogo#595]
I guess you sere right, full-blown croogo site's only affordable to proficient ones for it uses cakePHP architecture and library (may be more) with great many folders (most of which have empty files), but I think as far as croogo posesses dashboard (which is for dummer ones) there has to be some guide/tutorials or few examples of handlind it properly.
For example It is easy to create (deal with) dynamic blocks in Get-Simple cms (just to put block wherever you want depending on page slugs as well) and thus make pages looking individual but it is so problemsome (to me, for I don't know cake PHP) to assign blocks to homepage only.
I decided If I don't come up with these few basic configurations issues I'll better go choosing more user friendly confugurable scripts (tiny article :))

**Comment by rchavik** [comment]
Unfortunately yes, despite the 'tagline', croogo is right now more dev oriented.
