### ISSUE TITLE
Admin Dashboards still not found

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#597]
Tested on master branch, dashboards still not working:

2014-12-18 22:58:01 Error: [MissingControllerException] Controller class DashboardsController could not be found.
Exception Attributes: array (
  'class' => 'DashboardsController',
  'plugin' => NULL,
)
Request URL: /admin/dashboards
Stack Trace:
#0 /Library/WebServer/Documents/test/croogo220/webroot/index.php(105): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2014-12-18 22:58:10 Error: [MissingControllerException] Controller class DashboardsController could not be found.
Exception Attributes: array (
  'class' => 'DashboardsController',
  'plugin' => NULL,
)
Request URL: /admin/dashboards
Stack Trace:
#0 /Library/WebServer/Documents/test/croogo220/webroot/index.php(105): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

**Comment by slightlychilled** [comment]
Hi, Yes this is resolved - in part. Sorry for the late reply. Have been travelling. It's working after the manual activation of the plugin, although there are no DOCS on how to use it.

**Comment by rchavik** [comment]
Moving this to 2.3 as the activation of Dashboards by default should happen there.

Re: docs, would be nice if you could help with it.

**Comment by slightlychilled** [comment]
Hi. Would love to help with the DOCS but can't seem to get things working. Have tried editing the feed URL for the Croogo News block and it fails. No content is pulled in. Would happily create some docs for you if I knew where to start with this.

**Comment by slightlychilled** [comment]
Any suggestions on how to add/modify blocks in dashboards would be great - just to get me started.

**Comment by rchavik** [comment]
A quick notes on top my head. Warning: will contain typo and untested code:

## Registering a dashboard block

This is done in <Plugin>/Config/admin_dashboard.php.  It's a typical cakephp config file.  The array key is the dashboard identifier and the value contains the dashboard block setting.  It accepts 3 options:
  - title
  - element: Path to element file containing the Dashboard html code
  - column: Valid values:  CroogoDashboard::LEFT, CroogoDashboard::RIGHT, CroogoDashboard::FULL

Once that is registered, the block should be rendered in the dashboard page.

## Displaying dashboard contents

This is entirely left up to you.  The example plugin has a static block.  The default Dashboards plugin provide the croogo blog's newsfeed. The javascript code retrieves the https://blog.croogo.org/promoted.rss, parses the XML and display the blog title as a link.

You can do other stuff of course:

```php
// Plugin/YourPlugin/Config/admin_dashboard.php

$config = array(
    'dashboard.latest_comment' => array(
        'title' => 'Latest Comment',
        'element' => 'YourPlugin.dashboards/latest_comments',
        'column' => CroogoDashboard::LEFT,
    ),
);
```

```php

// Plugin/YourPlugin/View/Elements/dashboard/latest_comments.ctp

// Display $comments in the block
$comments = isset($comments) ? $comments : array();  // when $nodes does not exist, set it to an empty array
foreach ($comments as $comment):
   echo $this->Html->para(null, $comment['Comment']['title'];
endforeach;

```

`$comments` need to be populated somewhere else.  One alternative is to write a custom component and hook it to the `DashboardsController`:

```php
// Plugin/YourPlugin/Config/bootstrap.php

Croogo::hookComponent('Dashboards.Dashboards', 'YourPlugin.LatestComments');
```

```php
// Plugin/YourPlugin/Controller/Component/LatestCommentsComponent.php

class LatestCommentsComponent extends Component {

    public startup(Controller $controller) {
        $comments = ClassRegistry::init('Comments.Comment')->find('list', array(
            'order' => 'created desc',
            'limit' => 10,
        ));
        $controller->set(compact('comments')); // send the retrieved comments to the view so that it can be picked up by the dashboard block
    }
}
```

**Comment by rchavik** [comment]
Made above comment into page in PR: croogo/docs#17

Now published in http://docs.croogo.org/2.0/en/developers/core-plugins/dashboards.html

**Comment by rchavik** [comment]
Related: croogo/app#17
