### ISSUE TITLE
Cannot delete theme

### ISSUE THREAD

**Issue by oldskool** [croogo/croogo#598]
When attempting to delete a theme from the /admin/extensions/extensions_themes page, a JavaScript error is thrown when clicking any of the delete buttons:

> Uncaught SyntaxError: Unexpected token }

The problem appears to be that the confirmation dialog is not escaped, it gives output like this:

```
<a href="#" onclick="if (confirm("Are you sure?")) { document.post_54a66a7fc02db042466756.submit(); } event.returnValue = false; return false;" class="btn btn-danger"><i class="icon-trash icon-large"></i>Delete</a>
```

Using double quotes both for opening the `onclick` event and the confirmation message.
Updating it to either `confirm('Are you sure?')` or `confirm(\"Are you sure?\")` should fix it as far as I can tell.

**Comment by rchavik** [comment]
Yeah, I think this is due to missing `escape` or `escapeTitle` in the `$options` argument. Or maybe changing it to use `CroogoHelper::adminAction()`.

**Comment by oldskool** [comment]
Thanks for this! :+1:
