### ISSUE TITLE
Reflecting XSS vulnerability in administrative backend of Croogo v.2.2.0

### ISSUE THREAD

**Issue by sroesemann** [croogo/croogo#599]
Dear ladies and gentlemen.

Unfortunately, I haven't found a clear section on your webpage where to send security related issues to via mail so I'm using this platform.

I found a reflecting XSS vulnerability in your product Croogo v.2.2.0 residing in the administrative backend which could be abused to trick an administrator to click a crafted link which executes arbitrary HTML- and/or JavaScript-code.

I am releasing an advisory on my blog (without technical details). Please provide me an email address where I can send my informations to, so you can patch this vulnerability. If I don't here anything from you until 17th January 2015, I am releasing the technical details as well.

Thank you.

Steffen Rösemann

**Comment by rchavik** [comment]
Hi Stefan,

Thanks for the report. Please forward the details to security@croogo.org.

**Comment by sroesemann** [comment]
Done! :-)

**Comment by rchavik** [comment]
Closing sine 2.2.1 has been released.

Thank you

**Comment by fgeek** [comment]
Could you add a web page for information how to report security issues in the future, thanks!

**Comment by rchavik** [comment]
Hi,

We've brought back the "Support" menu in croogo.org.

The URL https://croogo.org/security has also been created. It redirects to the same Support page (with direct anchor link `#security`).

Do you think it will suffice?

**Comment by sroesemann** [comment]
From my point of view, it will suffice as I researched your official webpage for such a hint on how to send reports like mine to you. Now I would know. Do you agree Henri?

**Comment by fgeek** [comment]
Yes, thanks! :)

**Comment by rchavik** [comment]
Cool.

Thanks for helping with security guys.
