### ISSUE TITLE
Does not work links in admin dropdown menu

### ISSUE THREAD

**Issue by marekrodkiewicz** [croogo/croogo#604]
For admin mobile layout does not work dropdown menu links located in panel header like Profile or Logout.
Menu is hidded before release tap on the screen.

It not works in Samsung galaxy ace 2 (android), iPhone 5 and chrome development tools (screen attached).
It works in HTC mozart (WP 7.8).

Steps:
1. Login http://demo.croogo.org/2.0/admin in mobile device or chrome development tools
2. Try to logout (top menu->admin->logout)

**Comment by marekrodkiewicz** [comment]
![croogo_issue](https://cloud.githubusercontent.com/assets/10455221/5670894/64ae3cae-9784-11e4-8727-c2ae9e3880da.png)

**Comment by rchavik** [comment]
Do you know whether this needs to fixed on croogo or twbs?

**Comment by rchavik** [comment]
Closing since 605 is open.  Fix scheduled for 2.2.2
