### ISSUE TITLE
Getting 500 internal server error while installing croogo cms

### ISSUE THREAD

**Issue by javed-codified** [croogo/croogo#608]
Hi,
I try to install croogo cms on server and i get 500 internal server error..

Thanks

**Comment by oldskool** [comment]
What does your error log say? A 500 error can have numerous reasons from insufficient permissions to insufficient memory or a missing dependency. There's no telling what the problem is without a log excerpt.

**Comment by rchavik** [comment]
Yes,

Please use Google Groups or IRC to get support.
