### ISSUE TITLE
MenuHelper::nestedLinks() and bootstrap 3 dropdown menus

### ISSUE THREAD

**Issue by phpMagpie** [croogo/croogo#609]
Just wondering if anyone is able to use the stock MenuHelper::nestedLinks() to generate bootstrap 3 dropdown menus?

If I specify `dropdown=>true` and supply a `dropdownClass` it gets applied when `depth=>1` which is the top level of the nested menu, not the child menus.  

    $this->Menus->menu('main', array(
      'dropdown'=>true, 
      'dropdownClass'=>'dropdown-menu', 
      'selected'=>'active', 
      'tagAttributes'=>array('class'=>'nav navbar-nav')
    ));

This means `dropdownClass` overwrites the `tagAttributes class` and my menu disappears from sight.

I can use the following link params to make a parent link ready for a `ul.dropdown-menu` ...

    [options:liAttr class=dropdown]
    [options:linkAttr id=about class=dropdown-toggle data-toggle=dropdown aria-haspopup=true role=button aria-expanded=false]

... but i can't add a class of `dropdown-menu` to the tagAttr without amending the core code, or creating a CustomHelper, which seems a little overkill.  Even then you would have to add the tagAttr params to the last link in the child ul, which isn't very elegant.

My other option is to use the folllowing jQuery to add that class, but that's a hack too:

    $('.navbar ul.nav ul').addClass('dropdown-menu');

**Comment by rchavik** [comment]
Can't recall anything special with twbs3 menu, but afair I managed to use modified Custom helper from nitishsidhar's theme.

The core MenuHelper itself can't really be easily used for generating twbs3 markup.
