### ISSUE TITLE
Extending Users.User and Taxonomy.Type

### ISSUE THREAD

**Issue by phpMagpie** [croogo/croogo#618]
I've created some basic plugins to allow me to extend Users and Content Types, however unless I change the core for admin_add and admin_edit actions my extra model data does not get saved because those actions use Model->save() not Model->saveAll()

I can easily go into the core and change the save type, but wondered if there is a cleaner way to do this?  Or, should we be updating the core so these actions use saveAll() as standard?

Thanks, Paul.

**Comment by phpMagpie** [comment]
P.S. In the past I submitted PR https://github.com/croogo/croogo/commit/8ca28045e23bf66ea4fc1206195f3835a196e330 for changing the save calls in Blocks.Blocks and it was accepted.

**Comment by dakota** [comment]
I don't see an issue with it (Although, I'd use `saveAssociated` instead)

**Comment by phpMagpie** [comment]
@dakota when is it better to use `saveAssociated` over `saveAll`?

**Comment by phpMagpie** [comment]
@dakota I stopped being lazy, visited the docs and now understand :)

The `saveAll` function is just a wrapper around the `saveMany` and `saveAssociated` methods. it will inspect the data and determine what type of save it should perform. If data is formatted in a numerical indexed array, `saveMany` will be called, otherwise `saveAssociated` is used.

So, if I know what action my save needs, use it and save a little bit of processing time.

**Comment by rchavik** [comment]
Would you be able to make a patch @phpMagpie ?

**Comment by phpMagpie** [comment]
Yeah, sure ...

**Comment by phpMagpie** [comment]
Would you prefer the PR to be structured as one patch for both Users and Types or two PRs?

Should we also look at modifying the save actions of other core models whilst doing this?  Is it ok to have the save call as saveAssociated even if the majority of the time it's only saving it's own data?

**Comment by rchavik** [comment]
> Would you prefer the PR to be structured as one patch for both Users and Types or two PRs?

I would prefer them to be on separate commits. It can however be submitted in the same PR.

> Should we also look at modifying the save actions of other core models whilst doing this? Is it ok to have the save call as saveAssociated even if the majority of the time it's only saving it's own data?

Relationships against core models are injected, so I think this makes sense.

**Comment by rchavik** [comment]
PR already merged eons ago.
