### ISSUE TITLE
cannot promote blog content from /admin/nodes page

### ISSUE THREAD

**Issue by egi** [croogo/croogo#619]
###### How to reproduce: ######

1. go to `/admin/nodes` page
2. create new blog and save
3. from `/admin/nodes` page, mark the checkbox of the new blog
4. choose `promote` from dropdown
5. submit

###### expected: ######
the new blog can be seen at frontpage (`/`)

###### result: ######
frontpage does not changed.

**Comment by egi** [comment]
forgot to mention the environment:

* cakephp/cakephp v2.6.1
* croogo/croogo v2.2.1

installed using composer on OSX, apache 2.4.9, php 5.5.14

**Comment by phpMagpie** [comment]
May be a caching issue for the block's find results.  Try installing the ClearCache plugin and clearing cache or simply edit and save a node after making the promote change.  

If this is the case, a patch is needed to refresh all node caches after BulkProcessing promote requests.

**Comment by rchavik** [comment]
Thanks.

I wasn't able to reproduce this, but yes, cache might be the culprit here.

**Comment by egi** [comment]
I can confirm that this is cache issue. I removed all files in /tmp folders every time after I promote a blog item from list page, the frontpage got refreshed and the item is displayed as expected.

Small note that promoting a blog item from edit page always works without the need to remove cache files.

**Comment by phpMagpie** [comment]
I would highly recommend having the ClearCache plugin in your projects for helping to debug cache related issues.  Makes life a lot easier :)

I use: http://github.com/ceeram/clear_cache

As for patching the issue, just need to figure out which cache is being cleared when saving a node that is not being cleared when BulkProcessing nodes.  Pointer: The cached find result will be created by BlocksComponent::blocks()
