### ISSUE TITLE
Migrate to Cakephp 3.0

### ISSUE THREAD

**Issue by Appsbender** [croogo/croogo#636]
I'm opening this ticket as a wishlist for Croogo 3.0 release in the near future. And would be more awesome if admin will be converted stable to the latest bootstrap version ;).

**Comment by rchavik** [comment]
For 3.0, there's a wip `3.0-wip` branch. For bootstrap, there's `2.3-twbs-upgrade`.

Both of those branches need some love. :)

**Comment by sakulstra** [comment]
I remember a discussion in irc about using http://emberjs.com/ or some similar language to refine the front/backend. Would be great to see this in 3.0 ;)

**Comment by sakulstra** [comment]
I remember a discussion in irc about using http://emberjs.com/ or some similar language to refine the front/backend. Would be great to see this in 3.0 ;)

**Comment by fahad19** [comment]
would be happy to help with a single-page app, preferably in React :)

**Comment by rchavik** [comment]
would appreciate any kind of help.

@fahad19 do you think it's worth doing an SPA **while** migrating to backend to 3.0 is feasible?

**Comment by Appsbender** [comment]
@fahad19 : Been watching croogo 3.0 and If I'm not mistaken there's much work to do since Cake 3.0 is introducing new ORM. Converting to single page app would be more awesome... I would suggest AngularJS ;)

**Comment by jhli** [comment]
I'd loce to see real CMS with cascading element schemas, asset pools, staging and multi tenant, multi language content and page trees.

While react looks nice I'd be careful to not add too many mandatory technologies/layers.

Cake 3 cells, rails like partials, CRUD and TWBS utilizibg extends() instead if div/class soup seem interesting to me. Maybe Twig.

**Comment by jhli** [comment]
I'd also play the devils advocate and wonder if quockapps / croogo could not work more collaboratly.

**Comment by PaulPrecept** [comment]
This thread shows the Croogo v3 was a work in progress in March 2015.  Two years on from that, how close are we to being able to use Croogo and CakePHP 3 on a production site?

I LOVE Croogo to bits, using it daily, although with a heavily customised client facing prefix installed and quite a few core hacks.  But I'm really concerned about how far my Croogo sites are behind with CakePHP.  

I really don't want to ditch if it's going to be another 6months+ before there is a production ready version of Croogo which uses CakePHP 3 then I'm going to have to :(

Please understand, I'm not griping about how slow things are moving as I know this is an open-source project with people dedicating their own spare time, I'm just looking for a realistic roadmap/timeframe as to when Croogo v3 may be stable based on how long it has taken to get to this point.

**Comment by rchavik** [comment]
I'm using 3.x in product, for API + admin site.  Dakota uses 3.x for a classified site IIRC.

Most things are working.  At this time, the biggest work left is the Translate plugin.

As for timeline, I can't really say. If you can help, please jump in with the 3.x branch.

**Comment by PaulPrecept** [comment]
@rchavik thanks for the swift reply ... sounds like I need to get it installed, port across my customisations and see how I get on.  Looks like I've got a busy weekend ahead of me :)

**Comment by rchavik** [comment]
Sorry, no docs of the differences so far.

The best way to get started with 3.x is with a clean database.  We don't have an upgrade path yet.
If you need to use 3.x on an existing database, the easiest would be to install a new database and then
move the nodes, blocks, menus, etc to the new database by hand.

If you use ACL, the contents will need to be rebuild. Especially the `acos`, because the way
ACL is handled is totally different in 3.x i.e: action path format
```
2.x: controllers/Nodes/Nodes/admin_index
3.x: controllers/Croogo\Nodes/Admin/Nodes/index
```
I have documented the steps and recorded asciinema session to install 3.x in:

  https://blog.croogo.org/blog/croogo-300-alpha-2-released

**Comment by rchavik** [comment]
Closing since [3.0.0 has been released](https://blog.croogo.org/blog/croogo-300-released)
