### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by phpedinei** [croogo/croogo#642]
On distributed servers settings.json the file does not work well.
I need to install all the servers in any extension because of it.

This is a problem I am facing to the site http://postalsaude.com.br

**Comment by rchavik** [comment]
Yes, we will likely remove this and use other mechanism for this purpose.

**Comment by phpedinei** [comment]
My idea is to write to the settings last updated menus, settings.json or anything that gets cached. And write to BD this update. Whenever you open the site verify that time on the settings.json. If diverges, remove the cache, and create again.

**Comment by phpedinei** [comment]
But changing the settings.json for cake cache is good because it will be not always on filecache.

**Comment by cdepre-sme** [comment]
settings.json has been removed in 3.0

**Comment by rchavik** [comment]
Closing as per comment
