### ISSUE TITLE
Add the Timestamp behavior to tables

### ISSUE THREAD

**Issue by Wouter0100** [croogo/croogo#644]
We don't need to forget to add the Timestamp behavior in all tables which are using the "created" and "updated" fields.

**Comment by rchavik** [comment]
Maybe we can think about renaming `updated` fields to `modified` as it's more common in cake.

**Comment by Marlinc** [comment]
That sounds like a good idea as well.

**Comment by Wouter0100** [comment]
Isn't that also default in Cake?

**Comment by Marlinc** [comment]
Yes but that's not the default in Croogo. There's stuff that currently depends on the ```update``` field.

**Comment by Wouter0100** [comment]
Yeah, okay. In that case, I don't think it has to be a part of the port. Just as an enchantment after the port is fully done.

**Comment by damien-biasotto** [comment]
I close this issue since #695 has been merged.
