### ISSUE TITLE
2.2 Croogo.Trackable and cake's created/modified don't work for (magic/non-resolved) HABTM

### ISSUE THREAD

**Issue by htstudios** [croogo/croogo#645]
If you don't define HABTM but simply use conventional database names to let cake bake detect those associations (thus don't resolve them into multiple basic HasMany/BelongsTo relationships) then you will have very simple HABTM but won't get:

1.) Croogo Trackable, e.g. you can't know who added/changed what associations
2.) created/modified, e.g. you can't know when that happend

I'd say flag als enhancement though non-cake/technical users might consider this a bug.

p.s.: It does only make sense if you also bake the HABTM model itself and have it listed, that way you can inspect the associations and when and who did add/modify them.

**Comment by jhli** [comment]
I might get to this ticket (and hopefully a fix) but it will be later this year.

**Comment by rchavik** [comment]
It would be good if this could be fixed. But yeah, it might be a limitation cake.

**Comment by rchavik** [comment]
This should be fixed in 3.x or 4.x. Ensure you have created the join table class and specify it as argument to the `through` belongsToMany options:

```php

class Groups extends Table {

  public function initialize()
  {
    $this->belongsToMany('Users', [
      'through' => 'GroupsUsers', // this class must exists and has Trackable attached
    ]);
  }
  // ...
```
