### ISSUE TITLE
Rename Croogo/Croogo to Croogo/Core

### ISSUE THREAD

**Issue by Marlinc** [croogo/croogo#646]
@rchavik and I have been discussing on IRC about renaming Croogo/Croogo to Croogo/Core. This would make more sense as its the core of Croogo. It doesn't provide that much functionality on its own but relies on the other core plugins to become the CMS.

**Comment by Wouter0100** [comment]
And it is a great idea, yeah. Currently some paths are really confusing (Croogo/Croogo.Croogo and so on). -

**Comment by Wouter0100** [comment]
Why not rename it to Croogo, instead of Croogo/Croogo or Croogo/Core?

**Comment by rchavik** [comment]
Won't that conflicts with other core plugins, like `Croogo\Nodes`?

**Comment by Marlinc** [comment]
No it won't actually. ```Croogo`` and ```Croogo/Nodes``` are seen as two completely different plugins. 

Actually renaming the core to ```Croogo``` will however give de benefit of easy inclusion using Composer.

It would make it possible to load Croogo with one plugin load instead of two like shown in https://gist.github.com/Marlinc/9d6b1a7a1b470cb3b78d.

It would become possible to load Croogo by just doing:

```php
Plugin::load('Croogo', ['bootstrap' => true]);
```

**Comment by Marlinc** [comment]
How about renaming ```Croogo/Croogo``` to just ```Croogo```.

**Comment by rchavik** [comment]
I'm not convinced that this is the way to go.  Correct me if i'm wrong, but I gather that the primary reason to do this is that we want to do: `Plugin::load('Croogo');` and have it setup autoloading for the rest of other core plugins in [Croogo/config/bootstrap.php](https://github.com/croogo/croogo/blob/3.0/config/bootstrap.php).

I feel that we should take advantage of composer's autoloading instead; i.e: in `APP/config/bootstrap.php` we call `Plugin::load('Croogo/Core')` and have it bootstrap croogo like in 2.x with the exception of plugin paths being managed by composer.

I know that this requires us to split the plugins into separate (readonly) repos.  A lot of work, but I think splitting them would be better in the long run.

**Comment by Wouter0100** [comment]
Any updates on this? `Croogo/Croogo` seems to be renamed to 'Croogo/Core' already, which seems very nice.

**Comment by rchavik** [comment]
Yeah.. closing
