### ISSUE TITLE
2.2 core views / bake templates: selects should not autoselect the first option item on add view templates

### ISSUE THREAD

**Issue by htstudios** [croogo/croogo#647]
I think it is bad practice to have html selects automatically select the first html option in add view templates as it looks like the user did actually select something and may by accident submit forms where he did NOT actively select something.

E.g. the default behavior should be: empty => true and the empty form element should either say "Please select…". 

I think this can be fixed at bake level and in the core views. If you agree I'll prepare a patch.

**Comment by jhli** [comment]
Related: https://github.com/dereuromark/cakephp-setup/blob/master/Console/Templates/setup/views/form.ctp#L44

**Comment by jhli** [comment]
Related: https://github.com/cakephp/bake/pull/25#issuecomment-95168517

**Comment by dereuromark** [comment]
> Related: https://github.com/dereuromark/cakephp-setup/blob/master/Console/Templates/setup/views/form.ctp#L44

https://github.com/dereuromark/cakephp-setup/blob/cake2/Console/Templates/setup/views/form.ctp#L44

**Comment by rchavik** [comment]
Seems this is working as expected in 3.x
