### ISSUE TITLE
2.2. Rapidly smashing save/apply/save&new buttons triggers CSRF errors

### ISSUE THREAD

**Issue by ionas** [croogo/croogo#652]
Rapidly smashing save/apply/save&new buttons triggers CSRF errors.
If you accidentally double-click or double-tap you will get that.
The form request will save or validation will error it out, you never know. 

Solution: Shortly disable all form buttons for X seconds after hitting those then re-enable.
Why re-enable? If you have a very slow connection ON YOUR SIDE or there is a slow proxy in front of the webserver or some other misconfiguration / slowness, your request simply might get stuck somewhere in the network without really timing out (e.g. you get a timeout error on your side). In this special case you really want to hit those submit buttons again and it might succeed. 

What about impatient users then? Graphically it should not make a difference if they are disabled or not due to them. Cause when they re-enable those impatient users might feel the need to press those buttons again (non technical background).

I am not sure if to disable 1/2 second, 1second, 3 seconds or 5seconds?

**Comment by ionas** [comment]
As soon as the details on how long to disable are cleared up, I will prepare a PR!

**Comment by rchavik** [comment]
Let's try 5 seconds

**Comment by jhli** [comment]
Okay, I hope That setzing them to disabled does not featch new BS styles. Will try to prep a PR today.

**Comment by jhli** [comment]
Sorry for the delay. I' ll get to this soon!

**Comment by rchavik** [comment]
Not happening in 4.x
