### ISSUE TITLE
Themes plugin

### ISSUE THREAD

**Issue by champtheone** [croogo/croogo#654]
Hi, I am new to croogo and try to make a new theme, but there is not much on the internet, and I can't find where the themes is in the base croogo.

I tried then to install 2 themes. "Messy Business by Appsbender" and "Bootstrap Responsive Croogo by Nitish Dhar",

The screenshots images are not displayed on the theme admin panel.

And the themes are not in action even after trying to activate it.
Maybe if you provide a basic them, that I can copy and understand you api, i might be able to make a template out of it.

PS: I wrote in the docs issues, no one replied.

Thanks

**Comment by rchavik** [comment]
Please use Google Groups/IRC for questions.
