### ISSUE TITLE
Design inconsistencies in baked admin index pages

### ISSUE THREAD

**Issue by rakeshtembhurne** [croogo/croogo#661]
Newly baked admin index pages has following code/design issues
- **Blank Action:** An additional blank action is being added `$row[] = $this->Croogo->adminRowAction('', array(...)`
- **Additional `<td />s`:** Baked admin_index pages have actions in each `<td></td>` element which means we have excess number of `td`. Whereas in built-in tables (like Users list) actions are added in a single `td`, enclosed in `<div class="item-actions">...</div>`
- **Trash icon color:** It's should appear red, like on other built in admin pages
### Replicating issue

1 Bake models, controllers and views for a table inside your plugin
2 (Optional) Add additional class `table-bordered` in admin_index page to see the effect (see the screenshot).

Screenshot: Baked
![croogo_bake_design_incositencies](https://cloud.githubusercontent.com/assets/1090611/7794067/18b4f100-02e4-11e5-8e1c-60a18f01720a.png)

Screenshot: Original
![croogo_admin_index_original](https://cloud.githubusercontent.com/assets/1090611/7794106/6e922e62-02e4-11e5-9b04-ac5325ed756c.png)

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
