### ISSUE TITLE
Changing front-end theme throws warnings for some time

### ISSUE THREAD

**Issue by rakeshtembhurne** [croogo/croogo#662]
When I install a new theme (tried with [Flatly theme](https://github.com/sherwinrobles/Flatly-Theme) ), and change theme from admin, it throws some warnings in header and sidebar.

`Warning (512): Method CustomHelper::menu does not exist [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper.php, line 192`

I tested it in at least two machines, and thing to note is that this error goes away after some time. I guess this is some kind of cache issue. The issue is experienced when we first time activate Flatly theme from default. 
- OS: Ubuntu 14.04
- Server version: Apache/2.4.7 (Ubuntu)
- Browser: Chrome

Also not sure if it's theme's issue or Croogo's. Can someone confirm that this is happening for others as well?

![custom_helper_error](https://cloud.githubusercontent.com/assets/1090611/7796604/973772cc-02fe-11e5-8570-d0fc14ac9353.png)

**Comment by rchavik** [comment]
Related #400

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
