### ISSUE TITLE
3.0 Core Behaviors

### ISSUE THREAD

**Issue by rchavik** [croogo/croogo#669]
Many of the Croogo/Core behaviors need upgrade:
- [x] Trackable
- [x] ~~Params~~ Replaced By Database\Type\ParamsType
- [x] ~~Encoder~~ Replaced By Database\Type\EncodedType
- [x] Publishable
- [x] Aliasable - Done by @Marlinc 
- [x] Url - Done by @Marlinc 
- [x] Copyable
- [ ] BulkProcess - In progress in #682
- [x] CroogoAcl - Depends on `Croogo\Acl`

**Comment by rchavik** [comment]
These renames renders croogo unbootable. Don't merge yet

**Comment by phpMagpie** [comment]
Related question: 
Does /croogo/app/Console/add_submodule need updating to pull CakePHP 2.7 rather than master branch (currently 3.0.10)?

**Comment by rchavik** [comment]
Yes. That needs to be updated to use the 2.x branch

**Comment by Wouter0100** [comment]
CroogoAcl component is working now. All Acl stuff of Croogo should be working fine :+1: . Don't forget to use [this](https://gist.github.com/Marlinc/a5a6ad12b7f2c1965e48#file-database-sql-L411-L415) database change.

**Comment by Marlinc** [comment]
I've checked the checkbox for the CroogoAcl.
