### ISSUE TITLE
Occurs error when install croogo 2.xx

### ISSUE THREAD

**Issue by DBTHAI** [croogo/croogo#671]
hi everyone,

i am install croogo 1.5 by

Manual installation

Extract the archive. Upload the content to your server.
Locate your app directory, and rename the following files:
Config/database.php.install to database.php, and edit the details.
Config/croogo.php.install to croogo.php, and edit the details.
Config/settings.json.install to settings.json
You can access your admin panel at http://your-site.com/admin. The installer should display a page for you to create the administrative user

it work ok

but when i install croogo 2.x.x
i can't find croogo.sql from croogo-2.2.2\app\Config\Schema\sql. So i use croogo.sql from croogo 1.5
and install work fine but when i go to admin site
it occurs error as below:

AclNode::node() - Couldn't find Aro node identified by "Array ( [Aro0.model] => Role [Aro0.foreign_key] => 3 ) "
Error: An Internal Error Has Occurred.

Stack Trace
APP\Vendor\croogo\croogo\Acl\Controller\Component\AclFilterComponent.php line 200 → AclNode->node(array)
APP\Vendor\croogo\croogo\Acl\Controller\Component\AclFilterComponent.php line 179 → AclFilterComponent->getPermissions(string, integer)
APP\Vendor\croogo\croogo\Croogo\Controller\CroogoAppController.php line 248 → AclFilterComponent->auth()
APP\Vendor\croogo\croogo\Extensions\Controller\ExtensionsAppController.php line 23 → CroogoAppController->beforeFilter()
[internal function] → ExtensionsAppController->beforeFilter(CakeEvent)
APP\Vendor\cakephp\cakephp\lib\Cake\Event\CakeEventManager.php line 242 → call_user_func(array, CakeEvent)
APP\Vendor\cakephp\cakephp\lib\Cake\Controller\Controller.php line 674 → CakeEventManager->dispatch(CakeEvent)
APP\Vendor\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php line 187 → Controller->startupProcess()
APP\Vendor\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php line 165 → Dispatcher->_invoke(ExtensionsDashboardController, CakeRequest)
APP\webroot\index.php line 105 → Dispatcher->dispatch(CakeRequest, CakeResponse)

please help me to fix. Thank you so much.

**Comment by rchavik** [comment]
Don't use the sql from 1.5.  The CLI/web installer will create the schema using Migrations plugin and load the base data.

Please use Google Groups or IRC for support questions next time.

Thanks
