### ISSUE TITLE
Could not copy database.php file

### ISSUE THREAD

**Issue by emadz** [croogo/croogo#685]
I am try to install Croogo on Xampp Server on Mac pc. 

While installing it say;

Your tmp directory is writable.
Your config directory is writable.
PHP version 5.6.11 >= 5.3.10
CakePhp version 2.6.4 >= 2.5.4

On next screen for Step 1: Database;

Database Source: mysql
Database Host: localhost
Database Name: croogo
Database Username: root
Database Password: (empty)

Now, when i press its say, "Could not copy database.php file."?????

My Database is running... plz let me what is the issue.

**Comment by rchavik** [comment]
For some reason, the installer could not copy `APP/Config/database.php.install` to `APP/Config/database.php`.

Please use Google Groups or IRC for support.
