### ISSUE TITLE
Installing error !!!

### ISSUE THREAD

**Issue by jacop85** [croogo/croogo#689]
i'm trying to install Croogo via composer ... when i arrive to confirm admin account i got those errors :8ball: 

Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP\Vendor\cakephp\cakephp\lib\Cake\Utility\Validation.php, line 60]

Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP\Vendor\cakephp\cakephp\lib\Cake\Utility\Validation.php, line 60]

Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP\Vendor\cakephp\cakephp\lib\Cake\Utility\Validation.php, line 60]

**Comment by rchavik** [comment]
As a workaround, downgrade your cakephp first.

**Comment by jacop85** [comment]
it should be cakephp 2.6.11 last release for 2.6 verion. thank you (yes)
