### ISSUE TITLE
Port migrations to the new migrations plugin

### ISSUE THREAD

**Issue by Marlinc** [croogo/croogo#702]
We were waiting for cakephp/migrations#114 and cakephp/migrations#97 to be merged in order to implement migrations in CakePHP 3. This has been merged so now its possible to implement new migrations.

**Comment by Wouter0100** [comment]
Now we should also be able to create the installer upon this?

**Comment by Marlinc** [comment]
Yes, this will allow the installer to be implemented.

**Comment by Wouter0100** [comment]
cakephp/migrations#97 is merged in the mgirations plugin :)
