### ISSUE TITLE
Taxonomies plugin needs porting 

### ISSUE THREAD

**Issue by Wouter0100** [croogo/croogo#711]
We should be able to slim the taxonomies plugin down and improve it in many ways. 

IRC chat [here](https://gist.github.com/Wouter0100/1cb7db1cfddfba3dc942).

**Comment by Wouter0100** [comment]
Relations made when Taxonomies is made:
Types belongs to many Vacabularies
Vacabularies has many Terms

Nodes belongs to Types
Nodes belongs to many Terms

**Comment by Wouter0100** [comment]
Seems to be fully working in 3.0.0-beta.1? @rchavik @Marlinc In that case, can be closed! :)

**Comment by rchavik** [comment]
yup
