### ISSUE TITLE
Bug installing with SQLite

### ISSUE THREAD

**Issue by ribeirobreno** [croogo/croogo#712]
I've just tried to install Croogo 2.2.2 for the first time and stumbled upon this error message:

`Table users for model User was not found in datasource default.`

After a quick search i've found [this conversation](https://groups.google.com/forum/#!topic/croogo/eagvZRTv4Fo) and issue #329.

---

My suggestion is to remove the sqlite option from the installer until this bug is fixed or a workaround is provided.

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
