### ISSUE TITLE
Imagine plugin not compatible with croogo 2.2.2

### ISSUE THREAD

**Issue by jacop85** [croogo/croogo#714]
i'm using croogo 2.2.2 version with cakephp 2.6. I am trying to integrate xintesa Gallery plugin in my website. Using the command line "cake ext activate plugin Imagine" give the following error:

Error: Shell class ExtShell could not be found.
#0 C:\xampp\htdocs\bethania\Vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(200): ShellDispatcher->_getShell('ext')
#1 C:\xampp\htdocs\bethania\Vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 C:\xampp\htdocs\bethania\Vendor\cakephp\cakephp\app\Console\cake.php(47): ShellDispatcher::run(Array)
#3 {main} 
.
.
.
there is no longer available Imagine plugin for croogo 2.2.2 that use CakePHP 2.x.
i suggest for croogo team to add gallery plugin and all dependencies by default ... in this way croogo can take first place in the Powerful CMS World.

**Comment by rchavik** [comment]
It could be because the `CakeDC/Imagine` plugin has changed its default `master` branch for cakephp 3.x version.

Try manually changing the branch of `Imagine` to `1.x`.

Closing since I feel that gallery functionality should be done out of core.

**Comment by jacop85** [comment]
thanks a lot Chavik ... it work very good now :+1:

**Comment by jacop85** [comment]
thank you Chavik .... but still other problems whene i add new photo or attatchement in this url "http://bob.local/admin/assets/assets_attachments/add" and i get this errors now
 
#The requested address was not found on this server.

#Request blackholed due to "auth" violation.

**Comment by rchavik** [comment]
To debug, temporarily disable or unload `Security` component in `CroogoAppController`.

This is likely a problem with the Assets or Gallery plugin, and not with the core. So please create tickets in the appropriate repo.
