### ISSUE TITLE
Submit Contact Form Give Errors !

### ISSUE THREAD

**Issue by jacop85** [croogo/croogo#721]
i'm using croogo 2.2.2 with cakephp 2.7.5 ... whene i sumit contact form i get thos errors .

Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP\Vendor\cakephp\cakephp\lib\Cake\Utility\Validation.php, line 60]
Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP\Vendor\cakephp\cakephp\lib\Cake\Utility\Validation.php, line 60]
Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP\Vendor\cakephp\cakephp\lib\Cake\Utility\Validation.php, line 60]

**Comment by rchavik** [comment]
Similar to #689

Please downgrade your cakephp version for now.  Or submit a PR that changes all `notEmpty` to `notBlank`.

Thanks.

**Comment by Wouter0100** [comment]
Fixed in #727
