### ISSUE TITLE
adding Attachments to nodes using CKeditor

### ISSUE THREAD

**Issue by yazanT** [croogo/croogo#725]
First thumbnails are no longer available, you get the white file image instead 
![image-1](https://cloud.githubusercontent.com/assets/15890744/11213114/f8f3cf6e-8d42-11e5-8285-516d6c879597.JPG)

 And uploading an attachment from the CKeditor is working but after that u can'y attach any image you have to close and retry. cause the url is changing in the pop-up
Using Croogo 2.2.2
![image-2](https://cloud.githubusercontent.com/assets/15890744/11213200/5ba58936-8d43-11e5-9600-5e952339ef91.JPG)

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
