### ISSUE TITLE
CKeditor not working

### ISSUE THREAD

**Issue by mangravity** [croogo/croogo#732]
Hi guys!
USE: croogo v 1.5.5 // php 5.3.0
## I ran into a problem on the site so that I did not show a visual editor (Integrates CKEditor WYSIWYG editor into Croogo). That portion of the log that points to it, but I can not figure out what exactly the problem. 

Request URL: /admin/eWebEditor/sql.asp
Stack Trace:
#0 _my-site.com_/app/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2015-11-28 22:19:12 Error: [MissingControllerException] Controller class FckeditorController could not be found.
Exception Attributes: array (
  'class' => 'FckeditorController',
  'plugin' => NULL,
)
Request URL: /admin/fckeditor/SqlIn.asp
Stack Trace:
#0 _my-site.com_/app/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2015-11-28 22:19:12 Error: [MissingControllerException] Controller class FckeditorController could not be found.
Exception Attributes: array (
  'class' => 'FckeditorController',
  'plugin' => NULL,
)
Request URL: /admin/fckeditor/SqlIn.asp
Stack Trace:
#0 _my-site.com_/app/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2015-11-28 22:19:12 Error: [MissingControllerException] Controller class ImageController could not be found.
Exception Attributes: array (
  'class' => 'ImageController',
  'plugin' => NULL,
)
Request URL: /admin/image/Sql.asp
Stack Trace:
#0 _my-site.com_/app/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2015-11-28 22:19:12 Error: [MissingControllerException] Controller class ImageController could not be found.
Exception Attributes: array (
  'class' => 'ImageController',
  'plugin' => NULL,
)

---

There were no changes, just the next day ceased to appear. Show you how to fix it.

**Comment by Wouter0100** [comment]
Maybe a good idea to upgrade to a later version of Croogo and PHP (it's already EOL for more then a year).
