### ISSUE TITLE
auto slug for unicode working improperly

### ISSUE THREAD

**Issue by lequy1010** [croogo/croogo#739]
example: when i type "Điện thoại di động" , slug become "din-thoi-di-dng"
infact, We want to show "dien-thoai-di-dong"

**Comment by anhtuank7c** [comment]
@lequy1010 You can see my behavior here: https://github.com/crabstudio/Ace/blob/master/src/Model/Behavior/SluggableBehavior.php

**Comment by lequy1010** [comment]
@anhtuank7c  thank you,
I have coding a Helper for it,<br>
I only log bug for croogo to fix it in next version

**Comment by rchavik** [comment]
Closed by 28f9ec3672af80e311277a3a6e0e4c9a5a4a3940
