### ISSUE TITLE
An Internal Error Has Occurred

### ISSUE THREAD

**Issue by saravananmalli** [croogo/croogo#740]
Hi,
I am installing the new version of croogo 2.2.2 i am getting the error (Cannot use 'String' as class name as it is reserved). I changed call name as an StringType I am getting error (An Internal Error Has Occurred) Any one can tel me what is the issue.

Thanks For Advance.

**Comment by rchavik** [comment]
Are you using PHP7?

**Comment by saravananmalli** [comment]
yes

On Fri, Jan 22, 2016 at 5:40 AM, Rachman Chavik <notifications@github.com>
wrote:

> Are you using PHP7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/croogo/croogo/issues/740#issuecomment-173772481>.
>



-- 
Regards
Saravanan

**Comment by rednax1994** [comment]
Will the use of php 7 mean we cannot install croogo??

**Comment by Wouter0100** [comment]
Not yet. Croogo 3 will be compatible with PHP7, if you ask me :)

**Comment by saravananmalli** [comment]
Thanks for your reply. I installed croogo2.2.2 in that installed gallery
plugin its not working can you tel me wt is the process to install gallery
plugin in croogo2.2.2.

On Wed, Feb 10, 2016 at 5:03 PM, Wouter van Os <notifications@github.com>
wrote:

> Not yet. Croogo 3 will be compatible with PHP7, if you ask me :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/croogo/croogo/issues/740#issuecomment-182362715>.
>



-- 
Regards
Saravanan

**Comment by rchavik** [comment]
Since croogo 2.x is using cakephp 2.x, it cannot run in php7. We'll need to wait until the cakephp 2.8 is ready in order to support php7.

**Comment by Wouter0100** [comment]
Cakephp 2.8 is already released, fully compatible with PHP7, @rchavik :).

**Comment by rchavik** [comment]
Ah good. Didn't realize that.

**Comment by saravananmalli** [comment]
I am not using php7. I am using php 4.5.1 and croogo version 2.2.2 i cant
able to install gallery plugin its shwoing error.

On Fri, Feb 12, 2016 at 6:04 AM, Rachman Chavik <notifications@github.com>
wrote:

> Closed #740 <https://github.com/croogo/croogo/issues/740>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/croogo/croogo/issues/740#event-548031057>.
>



-- 
Regards
Saravanan

**Comment by saravananmalli** [comment]
Can you tel me any one galley plugin not working ?
