### ISSUE TITLE
failed to open stream: File name too long

### ISSUE THREAD

**Issue by amohideen** [croogo/croogo#742]
go_visibility_blog_e0_ae_aa_e0_ae_bf_e0_ae_b0_e0_ae_a4_e0_ae_bf_e0_ae_af_e0_ae_ae_e0_af_88_e0_ae_9a_e0_af_8d_e0_ae_9a_e0_ae_b0_e0_ae_bf_e0_ae_a9_e0_af_8d_20_e0_ae_9a_e0_ae_bf_e0_ae_a9_e0_af_8d_e0_ae_a9_e0_ae_aa_e0_af_8d_e0_ae_aa_e0_ae_bf_e0_ae_b3_e0_af_8d_e0_ae_b3_e0_af_88_e0_ae_a4_e0_af_8d_e0_ae_a4_e0_ae_a9_e0_ae_ae_e0_af_8d_right_3): failed to open stream: File name too long [APP/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 356]

**Comment by Wouter0100** [comment]
Why do you have such a large name? The errors says it all..

**Comment by amohideen** [comment]
I'm not sure what name it refers to Sorry.. but the cache file, is it not a system created file? can you point me to wahat causes it please. This my second day with croogo (I now managed to mute it through croogo.php in Confic directory). I still want to know which file is causing it. Thanks.

**Comment by Wouter0100** [comment]
Oh, I see. Cache. Sorry, I'll take a look.

**Comment by rchavik** [comment]
maybe it's trying to cache a non latin UTF encoded titles

**Comment by amohideen** [comment]
my db collate is utf8, should I change and see this..

**Comment by amohideen** [comment]
yes.. it is a south asian language

**Comment by rchavik** [comment]
The long file name is due to this line: https://github.com/croogo/croogo/blob/master/Blocks/Controller/Component/BlocksComponent.php#L96.

Maybe we should simply use md5 or sha1 to hash the slug instead of inflecting it. It should be a little faster too.

Can you try changing line 90 from: 
```php
$slug = Inflector::slug(strtolower($request->url));
```
to
```php
$slug = sha1($request->url);
```

I also suspect the `strtolower` messed up the utf strings.

Can you give us a example of the URL that you were using?

**Comment by amohideen** [comment]
Thanks @rchavik it worked. 
I replced 
$slug = Inflector::slug(strtolower($request->url));
with
$slug = sha1($request->url);
in
myapp/Vendor/croogo/croogo/blob/master/Blocks/Controller/Component/BlocksComponent.php

Thanks...

**Comment by elbakai** [comment]
Hi,
When i use arabic character as a slug in the url, it give an error on 2016-01-28 04:18:02 Warning: Warning (512): SplFileInfo::openFile(/tmp/cache/queries/blocks/croogo_visibility_node_d8_a7_d9_84_d9_83_d9_86_d8_..........._a7_d9_86_d9_8a_ticker_news_3): failed to open stream: File name too long in [/home/almounta/public_html/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 356]

i use urldecode function to decode url chars like that :

$slug = Inflector::slug(strtolower(urldecode($request->url)));

and it give me a cache filename for blocks like : 
articles_عنواننموذجيتجريبيلمقالعشوائي

and it's work

**Comment by amohideen** [comment]
@elbakai 

try this it worked for me..

in
myapp/Vendor/croogo/croogo/blob/master/Blocks/Controller/Component/BlocksComponent.php
replce
$slug = Inflector::slug(strtolower($request->url));
with
$slug = sha1($request->url);

**Comment by amohideen** [comment]
and you can mute worning in myapp/Config/croogo.php

and change 

Configure::write('debug', 1) to Configure::write('debug', 0)
