### ISSUE TITLE
Contact form throws deprecated warning

### ISSUE THREAD

**Issue by amohideen** [croogo/croogo#744]
When submitting a filled in form, it throws a warning

Deprecated (16384): Validation::notEmpty() is deprecated. Use Validation::notBlank() instead. [APP/Vendor/cakephp/cakephp/lib/Cake/Utility/Validation.php, line 60]

**Comment by Wouter0100** [comment]
This has been fixed in #727, if you apply commit 6b6521a65c6219b1cb6a7617402aa008963d6cdf it should be fixed.
