### ISSUE TITLE
Full Featured CKEDITOR activation

### ISSUE THREAD

**Issue by amohideen** [croogo/croogo#745]
where do I make the change to get full featured CK editor? Not an Issue though..

**Comment by Wouter0100** [comment]
I was also searching for this, couldn't find it and changed it in the JS view. Maybe a nice feature to implement in 3.0, if it isn't implemented in 2.0 yet.

**Comment by amohideen** [comment]
it is only a matter of changing a word as far I understand (say from editor to editor1), the trouble is I can't find the file in which the code is.. third day with croogo...

**Comment by amohideen** [comment]
I found it.

Edit  YourApp/Plugin/CKeditor/webroot/js/wysiwyg.js
goto line 65 
change it from config.preset = 'standard' to config.preset = 'full'

**Comment by rchavik** [comment]
Yes, you're right.

Sorry I didn't see this earlier.

**Comment by rchavik** [comment]
Actually, I just remembered. You don't need to modify that file.

Check https://github.com/croogo/croogo/blob/master/Example/Config/bootstrap.php#L89-L114 and https://github.com/croogo/croogo/blob/master/Example/View/Example/admin_rte_example.ctp#L14-L22.
