### ISSUE TITLE
Invalid ID while adding a comment

### ISSUE THREAD

**Issue by amohideen** [croogo/croogo#748]
Invalid id error is thrown while adding a comment to a node and Posting a comment/Submitting.

**Comment by Wouter0100** [comment]
Which version of Croogo are you running and is the ID available in the POST-request? (since it [seems](https://github.com/croogo/croogo/blob/9df20225bc73a4d16fe171f7532e58b4718461ef/Comments/Controller/CommentsController.php#L198) like it's only thrown when `$foreignKey` is `null`)

**Comment by amohideen** [comment]
I'm using 2.2, I need to run through the code to see where it occurs.. what
should be the foreignKey (what value "which attribute from which table" is
assigned as foreignKey) ?

**Comment by rchavik** [comment]
Should be fixed in > 3.x
