### ISSUE TITLE
How to automate the promote and publish features

### ISSUE THREAD

**Issue by amohideen** [croogo/croogo#754]
I've written a code to insert values into the nodes table and I have set 1 for columns "promote" and "status", I have also taken care of all time columns, my insert works and I can see every record under "contents>list" in the admin panel as nodes. However my nodes are not visible for a normal user in the homepage until I have clicked on the edit and save buttons for each of them individually. I guess, the logic for this, is in the NodesController.php. I wonder if I can automate it and how?

**Comment by rchavik** [comment]
Try clearing cache?

Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
