### ISSUE TITLE
[3.0] Refactor shortcodes

### ISSUE THREAD

**Issue by dakota** [croogo/croogo#759]
Shortcodes need to be refactored. Currently they are interspersed amongst the various plugins with lots of duplicated code and no standard way of implementing them. It is also possible for plugins to have conflicting shortcodes.

I propose that a `ShortcodeManager` class is introduced that allows plugins to register a shortcode and a callable.

**Comment by josegonzalez** [comment]
Worth closing in favor of the more fleshed out #772.
