### ISSUE TITLE
Admin menu Issue on plugin

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#760]
Hi to the community and thanks for the continued work on Croogo.

I'm building a plugin using croogo 2.X and I have run into an issue with the admin menu. Current set up is as follows:

User Roles
1 Admin
2 Registered
3 Public
4 Client

Although I have created the admin nav using CroogoNav::add in the plugin file <plugindirectory>/Config/admin_menu.php in the standard way, the link shows up when logged in as the admin user but not when logged in as the client user.

Permissions have been set correctly using croogo permissions ACL/ACO etc... however, I have worked through the code and found the function linkIsAllowedByRoleId in the file Vendor/croogo/croogo/Acl/View/Helper/AclHelper.php

linkIsAllowedByRoleId
getAllowedActionsByUserId
linkIsAllowedByUserId

The action is allowed in the permission for the role id so I do not understand why the menu link is not being shown. Any thoughts / help would be greatly appreciated.

Thanks in advance.

S

**Comment by slightlychilled** [comment]
Anybody? It's been here for over a month and not one reply!

**Comment by rchavik** [comment]
it's a shot in the dark, but maybe try applying https://github.com/croogo/croogo/pull/764/files and see whether it resolves your problem?

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
