### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Bestrafung** [croogo/croogo#773]
I've built dozens of sites using other CMS systems such as Joomla and Wordpress but I've never used CakePHP or Croogo before so this is all new to me. I downloaded croogo-2.2.3.zip and uploaded the files to a folder named "app". When attempting to load index.php it redirects to /install and gets a 404/Not Found error. I've confirmed there isn't an "install" folder present and am unsure what to do now. I've also tried installation using git (just a blank white page with no errors) and composer (fails on the "composer install" step stating there is nothing to download/install). Any assistance would be much appreciated.

**Comment by dakota** [comment]
Croogo requires you to have rewrite rules enabled in your web server. You never directly access the `index.php` file. Please take a look at http://book.cakephp.org/2.0/en/installation/url-rewriting.html for instructions on how to configure it for various web servers.

**Comment by modularview** [comment]
Not very clear from the documentation, here is what I did:

1. Downloaded Croogo v2.2.2.zip from https://downloads.croogo.org/ 
2. Extracted the zip file and located it, as is, directly under the **web root** of my local server (please note that you located it inside an app folder maybe this caused the error?)
3. Created a new DB (utf8_unicode_ci) **manually**. This is an important step, without it I was keep getting "Internal error" during installation.
4. Run the installation from the browser by navigating to `http://localhost/[croogo-2.2.2-folder]`
5. In second step, edited the database name field to use the one I created manually in 3.
