### ISSUE TITLE
How to use croogo for educational institute exam report card make?

### ISSUE THREAD

**Issue by amostafiz** [croogo/croogo#778]
Dear Expert, as a new Croogo user i want to know, How to use croogo for educational institute exam report card make? [ like example: http://www.joygovtghs.edu.bd/student_results ] . i want to make student result another institute like this example. is it possible from any PLUGIN ? if it is, what plugin i should use? please help me.

**Comment by rchavik** [comment]
This question is probably better off asked in other channels, irc or google groups.

**Comment by amostafiz** [comment]
I'm tried all of section. But no replay. I think its not for good
responsibility for new user. Thank you.
