### ISSUE TITLE
[3.3] AuthComponent should be loaded before LoggedInComponent

### ISSUE THREAD

**Issue by Marlinc** [croogo/croogo#779]
CakePHP's `AuthComponent` should be loaded before `LoggedInComponent` to make sure that authentication based on `getUser` works.

The `AuthComponent` tries to get the current user from authenticate objects in the `startup` event. The `LoggedInComponent` however sets the user information before that (in `beforeFilter`). But even moving it isn't enough as the `LoggedInComponent` is being put higher up in the component list which causes it to be executed first.

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
