### ISSUE TITLE
can not understand croogo 

### ISSUE THREAD

**Issue by prabalthakur** [croogo/croogo#780]
hey , Croogo base is mvc and croogo itself is cms so for example how i will make a login page and its controller and model so it function properly at index of the project

**Comment by Wouter0100** [comment]
Croogo is a CMS, built using CakePHP (MVC). Croogo has the login build-in.

**Comment by prabalthakur** [comment]
thanks for reply

**Comment by prabalthakur** [comment]
Sir can you guide me how to  proceed , like how route work here in croogo and controller too ?

**Comment by prabalthakur** [comment]
i found that its done by nodecontroller now how to manage admin panel and use plugin. It would be great help for me as it will save my time .Please send me link or docs or examples  from where i can learn quickly

**Comment by rchavik** [comment]
See if this [video](https://youtu.be/gkpzKIuDuCM) helps
