### ISSUE TITLE
Compatibility with PHP7

### ISSUE THREAD

**Issue by zalsader** [croogo/croogo#785]
Are there any plans to make Croogo compatible with PHP7?
We could start off by removing assignment by reference for new objects

**Comment by Marlinc** [comment]
The new version of Croogo that is being worked on (3.x) is PHP 7 compatible

**Comment by zalsader** [comment]
Is 3.0 stable enough for production use?

**Comment by Marlinc** [comment]
Its still in development but there are a few companies actually building production websites using it

**Comment by zalsader** [comment]
Cool 😄 
I have just started using 2.1 in a new project with a PHP7 server. I may consider moving to 3.0 now.
Is there any documentation available for 3.0 yet?
Are there any plans to add the PHP7 support to 2.x?
Thank you.

**Comment by rchavik** [comment]
> I have just started using 2.1 in a new project with a PHP7 server. I may consider moving to 3.0 now.

We would appreciate help in making 3.0 stable. We have managed to get most ported, albeit with some missing/unported features.

You can try 3.0 now using `composer create-project croogo/app myapp 3.0.x-dev` 

> Is there any documentation available for 3.0 yet?

Not yet. We're very bad with docs unfortunately.

> Are there any plans to add the PHP7 support to 2.x?

I would try to make at least 2.3 runnable with php7 if I have time.

**Comment by rchavik** [comment]
> You can try 3.0 now using `composer create-project croogo/app myapp 3.0.x-dev`

Sorry, that was incomplete, please see below:

```
composer create-project croogo/app myapp 3.0.x-dev
cd myapp
bin/cake Croogo/Install.install -u dbuser -p dbpass -d Mysql -n dbname -h host -t 3306 admin pass
bin/cake server
```

If everything goes well, you can test by browsing to: http://localhost:8765/

See `bin/cake Croogo.Install.install --help`

**Comment by zalsader** [comment]
@Marlinc I've seen in the commit messages that 2.3 does support PHP7, is that official?

**Comment by rchavik** [comment]
> @Marlinc @rchavik I've seen in the commit messages that 2.3 does support PHP7, is that official?

That's the plan.  We need tests and bug reports though.
