### ISSUE TITLE
syntax error, unexpected 'new' (t_new) croogo

### ISSUE THREAD

**Issue by aditaa** [croogo/croogo#793]
running php 7 
during the install phase after imputing the database information i get this error 

`2016-12-10 01:15:58 Error: [ParseError] syntax error, unexpected 'new' (T_NEW)
Request URL: /install/install/database
Stack Trace:
#0 [internal function]: App::load('InstallManager')
#1 /var/www/html/croogo/Vendor/croogo/croogo/Install/Controller/InstallController.php(123): spl_autoload_call('InstallManager')
#2 [internal function]: InstallController->database()
#3 /var/www/html/croogo/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(InstallController), Array)
#4 /var/www/html/croogo/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/html/croogo/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallController), Object(CakeRequest))
#6 /var/www/html/croogo/webroot/index.php(105): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2016-12-10 01:15:58 Critical: Errors in CakeErrorController: Could not find %s.
`

**Comment by rchavik** [comment]
Croogo should run fine with PHP 7.

There was an issue with zip download 2.3.0 due to mismatch in app package. Maybe it's related.

- Are you using zip download?
- Or git?
- Which version?
