### ISSUE TITLE
Missing Database Table

### ISSUE THREAD

**Issue by hardy091** [croogo/croogo#794]
i'm working on Ubuntu 16.04. Please help me. Here error below
==================================================================
Missing Database Table

Error: Table types for model Type was not found in datasource default.
Notice: If you want to customize this error message, create app/View/Errors/missing_table.ctp
Stack Trace
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php line 3667 → Model->setSource(string)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php line 1394 → Model->getDataSource()
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php line 1490 → Model->schema()
APP/Vendor/croogo/croogo/Croogo/Model/Behavior/TrackableBehavior.php line 49 → Model->hasField(string)
APP/Vendor/croogo/croogo/Croogo/Model/Behavior/TrackableBehavior.php line 36 → TrackableBehavior->_hasTrackableFields(Type)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/BehaviorCollection.php line 145 → TrackableBehavior->setup(Type, array)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/BehaviorCollection.php line 66 → BehaviorCollection->load(string, array)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php line 781 → BehaviorCollection->init(string, array)
APP/Vendor/croogo/croogo/Croogo/Model/CroogoAppModel.php line 56 → Model->__construct(array, null, null)
[internal function] → CroogoAppModel->__construct(array)
APP/Vendor/cakephp/cakephp/lib/Cake/Utility/ClassRegistry.php line 169 → ReflectionClass->newInstance(array)
APP/Vendor/croogo/croogo/Croogo/Lib/CroogoRouter.php line 189 → ClassRegistry::init(string)
APP/Vendor/croogo/croogo/Nodes/Config/routes.php line 32 → CroogoRouter::routableContentTypes()
APP/Vendor/cakephp/cakephp/lib/Cake/Core/CakePlugin.php line 282 → include(string)
APP/Vendor/cakephp/cakephp/lib/Cake/Core/CakePlugin.php line 237 → CakePlugin::_includeFile(string, boolean)
APP/Vendor/cakephp/cakephp/lib/Cake/Core/CakePlugin.php line 226 → CakePlugin::routes(string)
APP/Vendor/croogo/croogo/Croogo/Lib/CroogoRouter.php line 218 → CakePlugin::routes()
APP/Config/routes.php line 29 → CroogoRouter::routes()
APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Router.php line 1267 → include(string)
APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Router.php line 596 → Router::_loadRoutes()
APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 219 → Router::parse(boolean)
[internal function] → Dispatcher->parseParams(CakeEvent)
APP/Vendor/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 147 → CakeEventManager->dispatch(CakeEvent)
APP/webroot/index.php line 105 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by rchavik** [comment]
need more info than this.
