### ISSUE TITLE
CakePHP 3.4 Support

### ISSUE THREAD

**Issue by rchavik** [croogo/croogo#797]
Mainly chores following https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html

**Comment by rchavik** [comment]
@phpMagpie this is pretty easy to do.  help me get it done :)

**Comment by phpMagpie** [comment]
Would love to help @rchavik, but up against it at work and never even installed CakePHP/Croogo 3 yet!!!   One day I will be chipping into the bigger tasks, I promise :)

**Comment by dakota** [comment]
FYI, croogo 3.0 HEAD runs just fine on Cake 3.4 :)

**Comment by rchavik** [comment]
> Would love to help @rchavik, but up against it at work and never even installed CakePHP/Croogo 3 yet!!! One day I will be chipping into the bigger tasks, I promise :)

Cool.

**Comment by rchavik** [comment]
> FYI, croogo 3.0 HEAD runs just fine on Cake 3.4 :)

Yes.  I'm referring to the list of deprecations listed on the Migration Guide :)

**Comment by djstearns** [comment]
I support this! Been using Croogo since Cake 1.3. Going to start on deprecations now. Do you have a roadmap?

**Comment by rchavik** [comment]
well, the goal for 3.0 is to get stable out, and we'd need tests ported and passing.
