### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by invincible09** [croogo/croogo#802]
Hey guys,

after running the installation, i tried going to the admin dashboard but getting these errors

![screen shot 2017-03-13 at 9 02 42 pm](https://cloud.githubusercontent.com/assets/25088226/23881420/ac9d60f2-0830-11e7-9c13-560bee6c1f02.png)

thanks for the help!

**Comment by dakota** [comment]
Hey, what version of Croogo? And what is your environment?

**Comment by invincible09** [comment]
running the latest v2.3.2 Linux Environment

**Comment by rchavik** [comment]
I'm not sure what's going on, but try changing line 45 of `AclFilterComponent` to `static $config = array();`

**Comment by rchavik** [comment]
Stale, please try with 4.x.
