### ISSUE TITLE
Custom fields associated with new content types...

### ISSUE THREAD

**Issue by spencerthayer** [croogo/croogo#809]
Is it possible with Croogo 3 to finally be able to assign custom fields with content types in addition to a per-node basis?

**Comment by rchavik** [comment]
Not yet.  The 3.0 branch is just a port from 2.x to cakephp 3.  It does not really change/introduce new features.

**Comment by spencerthayer** [comment]
Understood. I was wondering about this as a feature way back during Croogo 1 point something. Is this on the list of things to do?

**Comment by rchavik** [comment]
Not really. But I'm open if you can provide a patch.
