### ISSUE TITLE
Erro on enable Croogo/Comments plugin

### ISSUE THREAD

**Issue by maiconpinto** [croogo/croogo#810]
I try croogo (3.0) when I enable Croogo/Comments show erro:

> Argument 1 passed to Croogo\Core\Router::build() must be an instance of Cake\Routing\RouteBuilder, string given, called in /home/maiconpinto/croogo/vendor/croogo/croogo/Comments/config/routes.php on line 19 and defined [ROOT/vendor/croogo/croogo/Core/src/Router.php, line 33]

Before:
```
// /home/maiconpinto/croogo/vendor/croogo/croogo/Comments/config/routes.php
$route->scope('/comments', [], function (RouteBuilder $route) {
        Router::build('/', ['controller' => 'Comments']);

        $route->fallbacks();
});
```

After fixed:
```
$route->scope('/comments', [], function (RouteBuilder $route) {
        $route->connect('/', ['controller' => 'Comments']);

        $route->fallbacks();
});`
```

**Comment by rchavik** [comment]
Fixed.

Thank you
