### ISSUE TITLE
Documentation about how to create a theme

### ISSUE THREAD

**Issue by maiconpinto** [croogo/croogo#813]
There is any documentation about how to create a theme (Croogo v3)? Or Console that create theme base and config?

**Comment by kadsyy** [comment]
as i'm aware there is no proper documentation on but since cakephp3 the theme work as a plugin. so your theme file should be located here ;

`mywebsite/plugins/Mycustomtheme/config/theme.json`

src and webroot folder are in the same location as config folder.

**Comment by rchavik** [comment]
Yes, sorry no docs yet.

You can view cakephp's documentation: https://book.cakephp.org/3.0/en/views/themes.html as all of those apply to croogo themes as well.

**Comment by maiconpinto** [comment]
Thanks @kadsyy and @rchavik 

I created a theme example, using [materializecss](http://materializecss.com). 

[MaterializeCSS theme for Croogo](https://github.com/maiconpinto/croogo-materializecss-theme)

I would like create a good theme, but I'm not expert. If you could help me to create a best theme, I appreciate so much.

**Comment by kadsyy** [comment]
i might be able to help since im more of a front end guy. plus my cake knowledge are quite limited i can learn here and there from you.
