### ISSUE TITLE
Plugin delete feature does not delete files, but shows success message

### ISSUE THREAD

**Issue by rakeshtembhurne** [croogo/croogo#819]
When trying to delete an extension, it shows **Success** message, but actually plugin files are not deleted.
![croogo_plugin_delete_issue](https://cloud.githubusercontent.com/assets/1090611/25326840/7e65055c-28ef-11e7-87ec-ef3e073beeb7.png)

**Comment by rchavik** [comment]
Can you create a PR or would you like me to directly pull from your fork?

**Comment by rakeshtembhurne** [comment]
Sent PR. Please ignore first commit. That branch is deleted from my repo.
