### ISSUE TITLE
Locale with 2 letters in frontend url

### ISSUE THREAD

**Issue by rajsaha6** [croogo/croogo#823]
I am new in Croogo and faced an issue with locale. I am using cakephp 2.9. Example, I want the site url like abc.com/es but currently its running as abc.com/esp. I tried to change the locale folder name from esp to es, it's not working. But if i changed that esp folder name to xyz, its working.  So all i got that any name with 3 letter its working fine but not the name with 2 letters. Any solution for this or i miss anything here?

**Comment by rchavik** [comment]
Version 2.x uses cakephp 2.x localization features. So i think this cannot be easily done.

I thought i have a workaround, but it seems I was wrong.
