### ISSUE TITLE
Default to login page

### ISSUE THREAD

**Issue by WWRFresource** [croogo/croogo#828]
I'd like to setup croogo to require visitors to login prior to viewing any of the sites contents. Is this possible? Would someone point me in the right direction, please? Thanks.

**Comment by rchavik** [comment]
Grant access of your `/' route, configurable via `Site.home_url` (it's by default `Nodes/promoted` to `Registered` role.  Revoke it from `Public` role.

**Comment by WWRFresource** [comment]
Still unsure how to do this... I've found Site.home_url in Vendor/croogo/croogo/Croogo/Lib/CroogoRouter.php:

`/**
 * Setup Site.home_url
 *
 * @return void
 */
	public static function routes() {
		$homeUrl = Configure::read('Site.home_url');
		if ($homeUrl && strpos($homeUrl, ':') !== false) {
			$converter = new StringConverter();
			$url = $converter->linkStringToArray($homeUrl);
			CroogoRouter::connect('/', $url, array(), array('promote' => true));
		}
		CakePlugin::routes();
	}

}`
But what am I actually changing?

**Comment by dakota** [comment]
@WWRFresource Nothing in the code. You need to change the permissions in the admin panel.
