### ISSUE TITLE
Remove 3 char from url when we got multilingual version

### ISSUE THREAD

**Issue by joshidomini** [croogo/croogo#829]
We got a Spanish version of site but the url is http://xyz.com/esp I need that to be http://xyz.com/es

Is there any way to do that with croogo. i can do it with direct cakephp but not while using croogo cms.

Please help.

**Comment by rchavik** [comment]
How did you do it with direct cakephp? If you let me know, perhaps I can try to find a similar workaround.

**Comment by joshidomini** [comment]
Thanks Rachman
I done it via this plugin https://github.com/CakeDC/i18n

**Comment by rchavik** [comment]
Try loading that plugin in Croogo and modify `Croogo/CroogoRouter::contentType()`

**Comment by joshidomini** [comment]
No Luck with that. Is there any way we can hire some one from your team . i mean a paid service to try to sort this issue.

**Comment by rchavik** [comment]
I can try.  Please contact me at my email address found in the commit logs.

**Comment by rchavik** [comment]
Addressed in 4.x
