### ISSUE TITLE
Upgrade to Croogo 3.0 beta 1 - how does it work

### ISSUE THREAD

**Issue by AlexL777** [croogo/croogo#831]
Hello Developers,

I discovered your CMS today and installed it in version 2.x.x. Now I would like to upgrade to 3.0.x, but do not understand how this should work.

Also, I can not create content in the backend because there are only Menus and Comments. I can not create blogposts. No further plugins with me at http://croogocms.wpzweinull.ch/myapp or what is it?

Thanks in advance.

**Comment by rchavik** [comment]
> I discovered your CMS today and installed it in version 2.x.x. Now I would like to upgrade to 3.0.x, but do not understand how this should work.

We have not established a clear migration path for 3.x yet as it is still not stable.

I would suggest to stick with 2.x, unless you're fluent with cakephp 3.x and willing to spend some time to debug 3.x issues.
