### ISSUE TITLE
I can not modify the permissions of the users, what is the solution ?

### ISSUE THREAD

**Issue by marcelopilone** [croogo/croogo#834]
I can not modify the permissions of the users, what is the solution ?, i tried 
sync up ..., but nothing happen, please helppp 
when I press the button it appears loading and never ending
![error](https://user-images.githubusercontent.com/13138425/29084303-f4d9619c-7c41-11e7-8942-a1ae0c131a91.png)

**Comment by rchavik** [comment]
try lturning on debug and ooking at the network activity using firebug or browser devtools.

then can you paste the output and tmp/logs/error.log here.

**Comment by marcelopilone** [comment]
This is the error, in the log of /tmp/logs/error.log looks fine

![1](https://user-images.githubusercontent.com/13138425/29119822-05138b18-7cde-11e7-8e13-7a6e622e09d0.png)
![2](https://user-images.githubusercontent.com/13138425/29119829-0be7cfee-7cde-11e7-9a44-19b8b5565d7f.png)

**Comment by rchavik** [comment]
the request is getting blackholed. whats you'r croogo and cakephp version?


might need to set `validatePost` and `csrfCheck` to false somewhere

**Comment by marcelopilone** [comment]
croogo : 2.3
cakephp: 2.9

in what file modified this validatePost and csrfCheck ?

**Comment by miketallroth** [comment]
These are both CakePHP options. The following links might help. The variables can be set in your controller's beforeFilter().

https://book.cakephp.org/2.0/en/core-libraries/components/security-component.html#form-tampering-prevention

https://book.cakephp.org/2.0/en/core-libraries/components/security-component.html#csrf-configuration

https://book.cakephp.org/2.0/en/core-libraries/components/security-component.html#disabling-the-csrf-protection

Using the browser back button rather than navigation in the app itself can also cause this type of error. Maybe that's obvious, but it still trips me up from time to time.

**Comment by marcelopilone** [comment]
thanks, i try this and then i comment if it works

**Comment by marcelopilone** [comment]
i try this but nothing happened ..

**Comment by rchavik** [comment]
What exactly did you try?

**Comment by rchavik** [comment]
I cannot reproduce this issue with croogo 2.3.2, cakephp 2.9.2, php 5.6.31.

Do you have custom code/plugin in your instance?

**Comment by marcelopilone** [comment]
[croogo.zip](https://github.com/croogo/croogo/files/1218034/croogo.zip)
[cakephp.zip](https://github.com/croogo/croogo/files/1218033/cakephp.zip)
I leave you attached croogo and cakephp, you could please modify the lines where you think the problem would be solved, thank you very much

**Comment by miketallroth** [comment]
I was able to reproduce the problem you saw. I fixed it in mine by adding a beforeFilter function to my Controllers/AppController.php file.

```
public function beforeFilter() {
    parent::beforeFilter();
    $this->Security->csrfCheck = false;
    $this->Security->validatePost = false;
}
```

This could probably be put into the AclAppController as well for a more focused fix, but to get you up and running the AppController will work.

**Comment by marcelopilone** [comment]
YOU ARE A GENIOUS, THE BEST DEVELOPER OF THE WORLD, THANKSSSSS

**Comment by rchavik** [comment]
Please note that the workaround entails disabling security mechanism. Ensure you're only disabling csrf and validatePost for `admin_toggle`.
