### ISSUE TITLE
Node Reordering with Tree Behavior

### ISSUE THREAD

**Issue by miketallroth** [croogo/croogo#836]
Similar to PR #790 as that relates to the LinksController, the NodesController is also affected by improper scoping with its use of the TreeBehavior. Links are "scoped" within their containing Menu. Nodes should be "scoped" within their Type.

This issue relates to #247 as well.

The hierarchy view works when the lft/rght values are valid. Even child content nodes appear indented under their parent node (when being displayed via /admin/nodes/nodes/hierarchy?type=page), however the interface does not currently support setting a parent, therefore parent / child relationships would have to be set manually in the database.

Also, the hierarchy view displays the moveup/down arrows as expected, and with the fix in PR #835  it will manipulate the lft/rght values properly.

Any existing installation would still need to have its lft/rght values manually fixed before this PR would help Node re-ordering. But at least this would allow new installations to maintain proper content ordering.

A follow-up issue could be to address the proper loading of the selection list in the parent field of the Node edit form. I don't have that code at this point, but I can look in to that as well. The parent field wouldn't have done any good anyway without proper scoping, so hopefully this is a roadblock out of the way.

keywords: MPTT

**Comment by rchavik** [comment]
PR merged
