### ISSUE TITLE
Postgres installation error on 3.0.x-dev

### ISSUE THREAD

**Issue by progLamer** [croogo/croogo#838]
Just gone through a new installation using croogo/app, the web installer and postgres database.

AttachmentTypeSeed generate database exception:
> Error: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "types_pkey" DETAIL: Key "(id)=(1)" already exists. 

That happens because TypesSeed insert autoincrement primary key but don't update primary key sequence. Also AttachmentTypeSeed don't insert primary key and get from sequence existing primary key value.

**Comment by rchavik** [comment]
Fixed
