### ISSUE TITLE
Reverting back to old permissions and roles

### ISSUE THREAD

**Issue by amohideen** [croogo/croogo#841]
Hi, Is there a way to revert back to the default permissions and role setting that ships with croogo?

I think I have messed up my settings I would like to restore them please

Thanks in advance

**Comment by rchavik** [comment]
For 3.x, try looking/modifying `Install/src/InstallManager::setupGrants()`.

For 2.x, you need to clean aros, acos, and aros_acos, and get `Install/Config/Data/[Aro|Aco|ArosAco]Data.php` loaded again. Read `Install/Model/Install.php` and you probably could write a custom shell to reload the acl.

don't do this in production :)

**Comment by amohideen** [comment]
Thanks. Synchronise tool worked for me. Thanks.
