### ISSUE TITLE
Problems with Setup 3.0.0 Beta

### ISSUE THREAD

**Issue by FlavioCesarino** [croogo/croogo#843]
I'm getting the next error when trying to install version 3.0.0-beta.1 from scratch.
How can I resolve this?
![1](https://user-images.githubusercontent.com/32959455/31824680-9437e2a6-b58e-11e7-8c63-48069f2669c3.jpg)

**Comment by FlavioCesarino** [comment]
I'm getting the next error when trying to install version 3 from scratch.
How can I resolve this?
![1](https://user-images.githubusercontent.com/32959455/31824622-5c522dce-b58e-11e7-8acf-da0a4b7a9349.jpg)

**Comment by Vadimushka** [comment]
Correct comand to 
`bin\cake Croogo/Install.Install ..`

**Comment by FlavioCesarino** [comment]
This step I did. Now that's missing.
What do I put in place of the word server?
![2](https://user-images.githubusercontent.com/32959455/31839454-e273b374-b5bf-11e7-85f6-b7f96e1b5e56.jpg)

**Comment by rchavik** [comment]
Please retry with 4.x
