### ISSUE TITLE
Problems with Setup 3.0.0 Beta 1 writing app file

### ISSUE THREAD

**Issue by FlavioCesarino** [croogo/croogo#845]
The Croogo is writing the wrong time to set up the app file.
After installation you need to rewrite manually.

![3](https://user-images.githubusercontent.com/32959455/31840908-12231208-b5c6-11e7-8b38-2f7fbbf5ee8d.jpg)
#843

**Comment by rchavik** [comment]
I don't understand how it can generate such weird output, can you share the exact command that causes this?

**Comment by FlavioCesarino** [comment]
According to installation instructions in:
https://blog.croogo.org/blog/croogo-300-alpha-2-released

The error occurs after the following command:
bin/cake Croogo/Install.install -u dbuser -p dbpass -d Mysql -n dbname -h host -t 3306 admin pass

**Comment by FlavioCesarino** [comment]
According to installation instructions in:
https://blog.croogo.org/blog/croogo-300-alpha-2-released

The error occurs after the following command:
bin/cake Croogo/Install.install -u dbuser -p dbpass -d Mysql -n dbname -h host -t 3306 admin pass

and the right thing should be, with the correct database settings.
![4](https://user-images.githubusercontent.com/32959455/31857136-70c990e0-b6b4-11e7-8945-e31f58b03c96.jpg)

**Comment by rchavik** [comment]
Maybe this is related to your terminal character encoding or something.

I don't use windows and do not know to reproduce this.  Sorry I can't help much.

**Comment by rchavik** [comment]
If you'd like to try to fix it, maybe debug https://github.com/croogo/croogo/blob/3.0/Install/src/InstallManager.php#L64-L67. Perhaps we need to use multibyte friend functions, eg:

http://php.net/manual/en/function.mb-ereg-replace.php

**Comment by FlavioCesarino** [comment]
Thanks, I use cake and I'm starting. I installed Croogo for testing on localhost.

**Comment by rchavik** [comment]
Please retry in 4.x
