### ISSUE TITLE
template upload not working

### ISSUE THREAD

**Issue by cocosuma** [croogo/croogo#849]
Hello,

Thanks for this version 3. i'm very excited about it.
i've started to play with it and would like to change the template. i've tried to uplaod a 3.0 template but get
An Internal Error Has Occurred
Error: An Internal Error Has Occurred.

How can we manually install a template? the documentation is still talking about croogo 2.

thanks

Fabien

**Comment by rchavik** [comment]
please the file you tried to upload

**Comment by cocosuma** [comment]
sorry for my late reply. 

i've tried this one : https://github.com/CVO-Technologies/croogo-bootstrap-theme

**Comment by cocosuma** [comment]
i've started to modify the core theme instead. it is working but I know that it's not clean :(

**Comment by rchavik** [comment]
If you're trying to develop a custom theme, please try this:

- Create an empty plugin/theme in `ROOT/plugins/MyTheme`: `bin/cake bake plugin MyTheme` - 
- Activate your new theme: `bin/cake settings write Site.theme MyTheme`

If you want to base on Croogo/Core, copy those files into your MyTheme, eg:
- cp vendor/croogo/croogo/Core/src/Template plugins/MyTheme/src
- cp vendor/croogo/croogo/Core/webroot/css plugins/MyTheme/webroot
etc

**Comment by humusdigital** [comment]
Hi, I'm using croogo 3 and I downloaded this theme https://github.com/CVO-Technologies/croogo-bootstrap-theme and I get some errors like : 

Error: The application is trying to load a file from the Croogo base theme plugin. 
Make sure your plugin Croogo base theme is in the www/.../plugins/ directory and was loaded.

I saved it in the folder /plugins/

any idea ?

**Comment by rchavik** [comment]
Please retry in 4.x and feel free to reopen if issue still exists in 4.x.
