### ISSUE TITLE
Error creating new user on Croogo 3.0.4 running on php 5.6

### ISSUE THREAD

**Issue by colorito76** [croogo/croogo#855]
I found that on the file: vendor\croogo\croogo\Users\src\Model\Table\UsersTable.php  line 305 appears the function random_bytes() which is only available on PHP7. This shots an InternalError on php 5.6 when creating new user on the backEnd

To solve it, I have done:
 
add the Security utility to the file:        ```use Cake\Utility\Security; ```

delete this line 305:                              ```return bin2hex(random_bytes($length));```
replace the line 305 with this:              ```return bin2hex(Security::randomBytes($length)); ```

I hope you would think that is it the correct solution

Pito

**Comment by rchavik** [comment]
That looks fine.

Please submit a pull request to this effect.

Thanks
