### ISSUE TITLE
Error : Installation: Database (3.0.4)

### ISSUE THREAD

**Issue by ahmadsyamim** [croogo/croogo#856]
Env : OSX - AMPPS
Croogo : v3.0.4

Desc :-
On click 'Next Step', error message displayed 'An Internal Server Error Occurred'.

Error Logs :-

> 2018-02-09 06:08:33 Warning: The connection is going to be closed but there is an active transaction.
> 2018-02-09 06:08:34 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:08:34 Error: You can ignore the above error during installation
> 2018-02-09 06:08:34 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:08:34 Error: You can ignore the above error during installation
> 2018-02-09 06:08:34 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:08:34 Error: You can ignore the above error during installation
> 2018-02-09 06:08:34 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:08:34 Error: You can ignore the above error during installation
> 2018-02-09 06:13:51 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:13:51 Error: You can ignore the above error during installation
> 2018-02-09 06:14:26 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:14:26 Error: You can ignore the above error during installation
> 2018-02-09 06:14:26 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:14:26 Error: You can ignore the above error during installation
> 2018-02-09 06:14:39 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:14:39 Error: You can ignore the above error during installation
> 2018-02-09 06:14:43 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo.settings' doesn't exist
> 2018-02-09 06:14:43 Error: You can ignore the above error during installation
> 2018-02-09 06:14:43 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo3.settings' doesn't exist
> 2018-02-09 06:14:43 Error: You can ignore the above error during installation
> 2018-02-09 06:14:44 Error: [Cake\View\Exception\MissingHelperException] Helper class LayoutHelper could not be found.
> Request URL: /install/data
> Referer URL: http://localhost/myapp/install/database
> Stack Trace:
> #0 /myapp/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(94): Cake\View\HelperRegistry->_throwMissingClassError('Layout', 'Croogo/Install')
> #1 /myapp/vendor/cakephp/cakephp/src/View/HelperRegistry.php(70): Cake\Core\ObjectRegistry->load('Layout')
> #2 /myapp/vendor/cakephp/cakephp/src/View/View.php(1087): Cake\View\HelperRegistry->__isset('Layout')
> #3 /myapp/vendor/croogo/croogo/Core/src/Template/Layout/error.ctp(24): Cake\View\View->__get('Layout')
> #4 /myapp/vendor/cakephp/cakephp/src/View/View.php(1196): include('/Applications/A...')
> #5 /myapp/vendor/cakephp/cakephp/src/View/View.php(1157): Cake\View\View->_evaluate('/Applications/A...', Array)
> #6 /myapp/vendor/cakephp/cakephp/src/View/View.php(812): Cake\View\View->_render('/Applications/A...')
> #7 /myapp/vendor/cakephp/cakephp/src/View/View.php(770): Cake\View\View->renderLayout('', 'error')
> #8 /myapp/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(364): Cake\View\View->render('error500', 'error')
> #9 /myapp/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(343): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
> #10 /myapp/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(200): Cake\Error\ExceptionRenderer->_outputMessage('error500')
> #11 /myapp/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(118): Cake\Error\ExceptionRenderer->render()
> #12 /myapp/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(100): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(PDOException), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
> #13 /myapp/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
> #14 /myapp/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
> #15 /myapp/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
> #16 /myapp/webroot/index.php(40): Cake\Http\Server->run()
> #17 {main}
> 
> 
> 2018-02-09 06:14:44 Warning: The connection is going to be closed but there is an active transaction.
> 2018-02-09 06:15:07 Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'croogo3.settings' doesn't exist
> 2018-02-09 06:15:07 Error: You can ignore the above error during installation

**Comment by ahmadsyamim** [comment]
Also, if i changed the DB Host to '127.0.0.1', the **config/app.php** file will be **corrupted on line 223**

> Parse error: syntax error, unexpected '.0' (T_DNUMBER), expecting ']' in /Applications/AMPPS/www/cms/2018/myapp/config/app.php on line 223

**Comment by rchavik** [comment]
Should be fixed in 3.0.6
