### ISSUE TITLE
Bad Request to Croogo 2.3.2 and CakePHP 2.10.5

### ISSUE THREAD

**Issue by Vadimushka** [croogo/croogo#863]
[ru]
При ajax запросах возникает ошибка bad request, помогает только если поставить где надо вот такую конструкцию 
`$this->Security->validatePost = false;`

[en] by  Google Translate
When ajax requests there is a bad request error, it only helps if you put where you need this kind of construction
`$this->Security->validatePost = false;`

**Comment by rchavik** [comment]
Hi,

We should not do blanket `validatePost = false`, which ajax request is giving these errors?

**Comment by Vadimushka** [comment]
all ajax request

**Comment by rchavik** [comment]
Hmm, I tested adding a new Custom Fields in `admin/nodes/edit` and it seems to load via ajax the form ok.  Saving also works.

I need more info because I can't reproduce.
