### ISSUE TITLE
How to select "terms"?

### ISSUE THREAD

**Issue by hkabir** [croogo/croogo#872]
How to select "terms" when adding or editing a node on croogo 3.0.5 as like croogo 2.o?

**Comment by miketallroth** [comment]
When editing (or creating) a Node, you should see both the Node tab and the Terms tab. Switching to the Terms tab should display the Categories and the Tags fields. When I click on the field, a dropdown shows the available Categories. I have an install of 3.0.5 that is working. Can you describe what you are seeing in your install?

![screenshot from 2018-09-01 22-32-12](https://user-images.githubusercontent.com/4733342/44951920-1bf0cb80-ae37-11e8-8212-8c65961f330a.png)

**Comment by hkabir** [comment]
Thanks a lot for your response. I just found the "Terms" tab, for some unknown reason which was not showing before. But now I can only see the "Categories", but not the "Tags" to select. I am not sure what is the problem.
![image](https://user-images.githubusercontent.com/330789/44992119-25557180-afb8-11e8-94d0-e8bf2eaff4e5.png)

**Comment by hkabir** [comment]
Can you also tell, why "WYSIWYG" not showing during adding a node, though I have enable it from setting?
 
![image](https://user-images.githubusercontent.com/330789/44992279-9dbc3280-afb8-11e8-9cb4-30ad317a9696.png)

**Comment by miketallroth** [comment]
> Thanks a lot for your response. I just found the "Terms" tab, for some unknown reason which was not showing before.

It is possible that you were initially adding / editing a Page. By default, Pages do not have any taxonomy enabled, therefore the Terms tab would not show up. Nodes and Blogs DO have both taxonomies (categories and tags) enabled.

> But now I can only see the "Categories", but not the "Tags" to select. I am not sure what is the problem.

It looks like you may have added a new content type (I do not recognize the characters in the first tab in your screenshot). When creating this new type, you may have only enabled the categories taxonomy. Can you try to edit your content type again and ensure both taxonomies are selected?

If this isn't a new type, but rather a translation, perhaps we've got an i18n module issue that needs to be addressed.

> Can you also tell, why "WYSIWYG" not showing during adding a node, though I have enable it from setting?

I can reproduce this issue as well. I'll try to investigate, but can't predict a timeline.

**Comment by miketallroth** [comment]
It looks like the Ckeditor plugin is not included as part of the base Croogo deployment. However, if you installed via composer, it can be added very simply by;

- running this command,
   - `composer require croogo/ckeditor:3.0.x-dev`
- then activating it via the admin panel under Extensions > Plugins,
   - click on the lightning bolt to activate it.

Reference: https://github.com/croogo/Ckeditor/tree/3.0

My assumption as to why it is not included is that this allows you to select the specific editor you want to plugin, or even create and use your own.

Hope this helps.

**Comment by hkabir** [comment]
The ckeditor it works fine now. Thanks

**Comment by miketallroth** [comment]
Let us know if you use Croogo in production. We'd love to see what you've done!
