### ISSUE TITLE
Croogo Plugins Missing Migrations Directories - 3.0.5

### ISSUE THREAD

**Issue by miketallroth** [croogo/croogo#874]
Acl, Extensions, FileManager, Wysiwyg

These four plugins are missing either the config/Migrations or the config/Seeds directories (or both) and each are causing the following permissions error when loading the admin plugins view. http://localhost/fvhp/admin/extensions/plugins

I can generate a PR for this if you agree to the solution. I'll plan to simply add the directories with an "empty" file within. I assume I should submit this to the 3.1 branch.

Mike

<b>Warning</b> (2)</a>: mkdir(): Permission denied [<b>ROOT/vendor/cakephp/migrations/src/ConfigurationTrait.php</b>
  | $forceRefresh = true
  | $migrationsPath = &#039;/home/miket/workspace/fvhp/vendor/croogo/croogo/Wysiwyg/config/Migrations&#039;
  | $seedsPath = &#039;/home/miket/workspace/fvhp/vendor/croogo/croogo/Wysiwyg/config/Seeds&#039;
  | $plugin = &#039;Croogo/Wysiwyg&#039;</pre><pre class="stack-trace">mkdir - [internal], line ??
  | Migrations\Migrations::getConfig() - ROOT/vendor/cakephp/migrations/src/ConfigurationTrait.php, line 74
  | Migrations\Migrations::run() - ROOT/vendor/cakephp/migrations/src/Migrations.php, line 304
  | Migrations\Migrations::status() - ROOT/vendor/cakephp/migrations/src/Migrations.php, line 142
  | Croogo\Core\Plugin::needMigration() - ROOT/vendor/croogo/croogo/Core/src/Plugin.php, line 521
  | Croogo\Core\Plugin::_loadData() - ROOT/vendor/croogo/croogo/Core/src/Plugin.php, line 315
  | Croogo\Core\Plugin::getData() - ROOT/vendor/croogo/croogo/Core/src/Plugin.php, line 346
  | Croogo\Core\Plugin::plugins() - ROOT/vendor/croogo/croogo/Core/src/Plugin.php, line 372
  | Croogo\Extensions\Controller\Admin\PluginsController::index() - ROOT/vendor/croogo/croogo/Extensions/src/Controller/Admin/PluginsController.php, line 55
  | Croogo\Core\Controller\Admin\AppController::invokeAction() - ROOT/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php, line 51
  | Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 119
  | Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 93
  | Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 108
  | Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
  | Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 104
  | Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65

**Comment by rchavik** [comment]
> I can generate a PR for this if you agree to the solution. I'll plan to simply add the directories with an "empty" file within. I assume I should submit this to the 3.1 branch.

Sounds good, though master branch would be fine
