### ISSUE TITLE
Git subtrees vs submodules

### ISSUE THREAD

**Issue by miketallroth** [croogo/croogo#875]
I'm trying to learn about git subtrees so that I'm not stomping on something in the croogo repo. I've been working with submodules now for about 2-3 years, and have become accustomed to them, however, I had never heard of subtrees until digging in to the croogo 3.x code.

After reading various articles, my understanding of the primary use case of subtrees is for a developer who wants to integrate a third party library into the code for ease of deployment. This makes for a one-step process for getting it checked out. It might also enable the use of composer to get the third level of repos incorporated into the final product (1-app, 2-library, 3-library plugins), meaning that the third level becomes part of the second level, and therefore just a simple require in the top level composer.json. In my reading, it seems that there is an emphasis on _third-party_. I understand that to mean where you _aren't_ committing to multiple levels of repos contemporaneously. As opposed to croogo where we _will_ make changes to both the library and the library plugins simultaneously.

Further on this primary use case, my understanding is that the library developers have plugins (level 3) which are typically built _independently_, either via a different project, or by a distinct third-party, then collected together into the library via subtrees, and the entire library (level 2) is published.

So, then in Croogo, it feels like the intention is to use the reverse process. Rather than develop at the low level and integrate up, it looks like the process in croogo is to develop at the high level, then separate down, at the final step.

Is this a correct analysis? What is the end goal of separating the plugins into multiple subtrees? If they eventually get flattened into the main library repo anyway, why bother having them separated? Is this simply an intermediate step to eventually using submodules, and keeping some sort of independent history until that point in time? Does this relate to composer's inability / unwillingness to perform recursive installs?

I apologize if these are dumb questions, as I said, I've never used subtrees before, so its entirely new to me. Also, I can't say I love submodules, but I believe they might have advantages over subtrees when the same set of developers are working on multiple levels of the app, as would be in the case of croogo where we would be responsible for both the library and the library plugins.

thanks!

**Comment by rchavik** [comment]
> What is the end goal of separating the plugins into multiple subtrees? If they eventually get flattened into the main library repo anyway, why bother having them separated?

The long term goal to try to make the plugins less interdependent between each other. For example, installing an instance without the Comments plugin.

The split repo are readonly.  We will never directly make changes there.  Everything will happen in the `croogo/croogo` repository.  The split is typically only 'sync'ed when we make a release (via Makefile target https://github.com/croogo/croogo/blob/master/Makefile#L159).

Secondly, by splitting them up, I'm hoping to make it easier to write unit tests.  You might have noticed, that writing tests for croogo is a bit of a pain. Eg: testing NodesController requires us to have Menus, Blocks, and Taxonomies plugin loaded.

And at this time, tests for 3.x is practically non-existent.

> Is this simply an intermediate step to eventually using submodules, and keeping some sort of independent history until that point in time?

Not really. The split repo is only intended as a readonly placeholder, where each will have its own `composer.json` and entry in the packagist.org.

It's similar to what the core cakephp team is doing for their split repos like `cakephp/collections`, or `cakephp/orm`.  These packages are developed in the main `cakephp/cakephp` repo, but are usable outside of cakephp framework if anyone wish it.

I hope this helps in clearing things up.
