### ISSUE TITLE
Croogo vs CakePHP post edit issue

### ISSUE THREAD

**Issue by tojibon** [croogo/croogo#877]
With CakePHP 3.5 and Croogo 3.0.x-dev having an issue with content edit. Ex: blog post.

If I save any content ex: /admin/nodes/nodes/add/blog with "Publish on" and "Un-publish on" field values (Selecting date by the datepicker) then when I go to edit that post I am getting error "Call to a member function format() on null Cake\Error\FatalErrorException"

But If I save any content keeping those fields "Publish on" and "Un-publish on" empty. Then when I go to edit that post IT WORKS!

Any IDEA?

**Comment by tojibon** [comment]
ok got it working with croogo version 3.0.5

**Comment by rchavik** [comment]
Glad to hear it
