### ISSUE TITLE
Example Helper Not Loading

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#883]
On a fresh install of Croogo 3.0.5, the Example Helper is not loading. Although the Croogo::hookHelper('Nodes', 'Example.Example'); is set in bootstrap.php the Helper Class Example cannot be found. This is also confirmed by the fact that none of the Helper Functions (afterSetNode, beforeNodeInfo, afterNodeInfo, etc) are working.

**Comment by rchavik** [comment]
This should work on 4.x
