### ISSUE TITLE
Link chooser fails on pagination

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#885]
Croogo 3.0.5 - default installation from download

When adding links to a menu, once you hit page 2 (pagination) you are taking out of the modal that is loaded and presented with a fresh screen. This breaks the add link feature.

Also, filter does not work either. Takes you to a new page.

**Comment by slightlychilled** [comment]
Looking at this, in Croogo 2 the link chooser opened up an iFrame, where as Croogo 3 is using Bootstrap Modal.

**Comment by slightlychilled** [comment]
Anyone have any ideas on why this is failing. I'm trying to debug and work out the issue, but I'm stuck.

**Comment by rchavik** [comment]
This should work on 4.x
