### ISSUE TITLE
Stored XSS in "Title" field - Vocabulary page

### ISSUE THREAD

**Issue by SegfaultMasters** [croogo/croogo#890]
**Description -**
There's no escape being done before printing out the value of `Title` in the Vocabulary page.

**croogo version -** v3.0.5

**Steps to reproduce -**

- Navigate to http://localhost/croogo/admin/taxonomy/vocabularies/add & add the below-shared payload as the values to the Title field.

   Payload -  `<img src=xss onerror=alert(1)>`

- Visit page http://localhost/croogo/admin/taxonomy/vocabularies, the payload will be triggered.

![image9](https://user-images.githubusercontent.com/2347778/51243426-8ea6b180-19a8-11e9-8cb6-9be409fc570b.jpg)

![image4](https://user-images.githubusercontent.com/2347778/51243430-91a1a200-19a8-11e9-8a05-797547b8d775.png)

**Comment by groovenectar** [comment]
This is likely related to this line in CroogoHtmlHelper.php: https://github.com/croogo/croogo/blob/master/Core/src/View/Helper/CroogoHtmlHelper.php#L227
