### ISSUE TITLE
Problem with PHP version higher than 7, for example 7.3 

### ISSUE THREAD

**Issue by mihau1** [croogo/croogo#893]
Installation script never finish on version higher than PHP 7.
So when i changed it to 5.6 or max v. 7 - everything is just working.
After finish installation on PHP <=7, and check that everything is working i swithing to higher version.

After changing to 7.3 version - there are some errors.
Maybe related with PHP extensions?
Sorry, but i cannot check what are those errors.

**Comment by rchavik** [comment]
Please try 4.0 branch.

Thanks.
