### ISSUE TITLE
Cancel button on edit link page fails.

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#894]
When editing a link for a menu, the cancel link button returns you to the incorrect URL.

**Comment by slightlychilled** [comment]
Added the following on line 120:
$this->set('cancelUrl', ['action' => 'index', 'menu_id' => $menu->id]);

**Comment by rchavik** [comment]
> Added the following on line 120:
> $this->set('cancelUrl', ['action' => 'index', 'menu_id' => $menu->id]);

Can you make a PR for 4.0 branch?
