### ISSUE TITLE
Displaying block content

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#895]
displaying content in a block, using the following in the body generates an internal error. Any ideas?

[node:recent_posts conditions=”Node.type:blog;Node.status:1” order=”Node.id DESC” limit=”5”]

**Comment by rchavik** [comment]
IIRC, this is cake 2.x format.

In 3.x, we need plural form for the table alias in `condition` and `order` clauses, eg:

`[node:recent_posts conditions=”Nodes.type:blog;Nodes.status:1” order=”Nodes.id DESC” limit=”5”]`
