### ISSUE TITLE
Block Content

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#896]
Prior to Croogo 3 you could extract a list of nodes by declaring the ID's of each content item in the block body. However, when trying to get this to work in Croogo 3 we get an internal error. What I have used int eh past is:

[node:carousel conditions="Nodes.id:2,3,4"]

Has this now changed?

**Comment by rchavik** [comment]
This is due to the way cake 3 changes its way of processing array conditions.

Try patching `vendor/croogo/croogo/Cor/src/Utility/StringConverter.php`:

```diff
diff --git a/Core/src/Utility/StringConverter.php b/Core/src/Utility/StringConverter.php
index 812895da..156c2a1e 100644
--- a/Core/src/Utility/StringConverter.php
+++ b/Core/src/Utility/StringConverter.php
@@ -83,7 +83,7 @@ class StringConverter
                     if (strpos($value, ',') !== false) {
                         $value = explode(',', $value);
                     }
-                    $stringArr[$stringElementE['0']] = $value;
+                    $stringArr[$stringElementE['0'] . ' IN'] = $value;
                 } else {
                     $stringArr[] = $stringElement;
                 }
```

**Comment by slightlychilled** [comment]
Thank you for the quick reply, that has fixed it perfectly.
