### ISSUE TITLE
$nodesForLayout

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#897]
In the past when generating content in blocks, you could access the result using $nodes_for_layout. I see that this has changed in croogo 3 to $nodesForLayout. However, when trying to access $nodesForLayout['recent_posts']; I now get the following output below. Has this changed, and how do I now access the content generated y the block content

[node:recent_posts conditions="Nodes.type:blog" order="Nodes.id DESC" limit="5"]

[
	'recent_posts' => object(Cake\ORM\Query) {

		'(help)' => 'This is a Query object, to get the results execute or iterate it.',
		'sql' => 'SELECT Nodes.id AS `Nodes__id`, Nodes.parent_id AS `Nodes__parent_id`, Nodes.user_id AS `Nodes__user_id`, Nodes.title AS `Nodes__title`, Nodes.slug AS `Nodes__slug`, Nodes.body AS `Nodes__body`, Nodes.excerpt AS `Nodes__excerpt`, Nodes.status AS `Nodes__status`, Nodes.mime_type AS `Nodes__mime_type`, Nodes.comment_status AS `Nodes__comment_status`, Nodes.comment_count AS `Nodes__comment_count`, Nodes.promote AS `Nodes__promote`, Nodes.path AS `Nodes__path`, Nodes.terms AS `Nodes__terms`, Nodes.sticky AS `Nodes__sticky`, Nodes.lft AS `Nodes__lft`, Nodes.rght AS `Nodes__rght`, Nodes.visibility_roles AS `Nodes__visibility_roles`, Nodes.type AS `Nodes__type`, Nodes.publish_start AS `Nodes__publish_start`, Nodes.publish_end AS `Nodes__publish_end`, Nodes.updated AS `Nodes__updated`, Nodes.updated_by AS `Nodes__updated_by`, Nodes.created AS `Nodes__created`, Nodes.created_by AS `Nodes__created_by`, Users.id AS `Users__id`, Users.role_id AS `Users__role_id`, Users.username AS `Users__username`, Users.password AS `Users__password`, Users.name AS `Users__name`, Users.email AS `Users__email`, Users.website AS `Users__website`, Users.activation_key AS `Users__activation_key`, Users.image AS `Users__image`, Users.bio AS `Users__bio`, Users.status AS `Users__status`, Users.updated AS `Users__updated`, Users.updated_by AS `Users__updated_by`, Users.created AS `Users__created`, Users.timezone AS `Users__timezone`, Users.created_by AS `Users__created_by`, Types.id AS `Types__id`, Types.title AS `Types__title`, Types.alias AS `Types__alias`, Types.description AS `Types__description`, Types.format_show_author AS `Types__format_show_author`, Types.format_show_date AS `Types__format_show_date`, Types.format_use_wysiwyg AS `Types__format_use_wysiwyg`, Types.comment_status AS `Types__comment_status`, Types.comment_approve AS `Types__comment_approve`, Types.comment_spam_protection AS `Types__comment_spam_protection`, Types.comment_captcha AS `Types__comment_captcha`, Types.params AS `Types__params`, Types.plugin AS `Types__plugin`, Types.updated AS `Types__updated`, Types.updated_by AS `Types__updated_by`, Types.created AS `Types__created`, Types.created_by AS `Types__created_by` FROM nodes Nodes LEFT JOIN users Users ON Users.id = (Nodes.user_id) LEFT JOIN types Types ON Types.alias = (Nodes.type) WHERE (Nodes.type = :c0 AND (Nodes.visibility_roles = ('') OR Nodes.visibility_roles IS NULL OR Nodes.visibility_roles like :c1) AND Nodes.status in (:c2,:c3)) ORDER BY Nodes.id DESC LIMIT 5',
		'params' => [
			':c0' => [
				'value' => 'blog',
				'type' => 'string',
				'placeholder' => 'c0'
			],
			':c1' => [
				'value' => '%"1"%',
				'type' => 'encoded',
				'placeholder' => 'c1'
			],
			':c2' => [
				'value' => (int) 1,
				'type' => 'integer',
				'placeholder' => 'c2'
			],
			':c3' => [
				'value' => (int) 2,
				'type' => 'integer',
				'placeholder' => 'c3'
			]
		],
		'defaultTypes' => [
			'Nodes__id' => 'integer',
			'Nodes.id' => 'integer',
			'id' => 'integer',
			'Nodes__parent_id' => 'integer',
			'Nodes.parent_id' => 'integer',
			'parent_id' => 'integer',
			'Nodes__user_id' => 'integer',
			'Nodes.user_id' => 'integer',
			'user_id' => 'integer',
			'Nodes__title' => 'string',
			'Nodes.title' => 'string',
			'title' => 'string',
			'Nodes__slug' => 'string',
			'Nodes.slug' => 'string',
			'slug' => 'string',
			'Nodes__body' => 'text',
			'Nodes.body' => 'text',
			'body' => 'text',
			'Nodes__excerpt' => 'text',
			'Nodes.excerpt' => 'text',
			'excerpt' => 'text',
			'Nodes__status' => 'integer',
			'Nodes.status' => 'integer',
			'status' => 'integer',
			'Nodes__mime_type' => 'string',
			'Nodes.mime_type' => 'string',
			'mime_type' => 'string',
			'Nodes__comment_status' => 'integer',
			'Nodes.comment_status' => 'integer',
			'comment_status' => 'integer',
			'Nodes__comment_count' => 'integer',
			'Nodes.comment_count' => 'integer',
			'comment_count' => 'integer',
			'Nodes__promote' => 'boolean',
			'Nodes.promote' => 'boolean',
			'promote' => 'boolean',
			'Nodes__path' => 'string',
			'Nodes.path' => 'string',
			'path' => 'string',
			'Nodes__terms' => 'text',
			'Nodes.terms' => 'text',
			'terms' => 'text',
			'Nodes__sticky' => 'boolean',
			'Nodes.sticky' => 'boolean',
			'sticky' => 'boolean',
			'Nodes__lft' => 'integer',
			'Nodes.lft' => 'integer',
			'lft' => 'integer',
			'Nodes__rght' => 'integer',
			'Nodes.rght' => 'integer',
			'rght' => 'integer',
			'Nodes__visibility_roles' => 'encoded',
			'Nodes.visibility_roles' => 'encoded',
			'visibility_roles' => 'encoded',
			'Nodes__type' => 'string',
			'Nodes.type' => 'string',
			'type' => 'string',
			'Nodes__publish_start' => 'datetime',
			'Nodes.publish_start' => 'datetime',
			'publish_start' => 'datetime',
			'Nodes__publish_end' => 'datetime',
			'Nodes.publish_end' => 'datetime',
			'publish_end' => 'datetime',
			'Nodes__updated' => 'datetime',
			'Nodes.updated' => 'datetime',
			'updated' => 'datetime',
			'Nodes__updated_by' => 'integer',
			'Nodes.updated_by' => 'integer',
			'updated_by' => 'integer',
			'Nodes__created' => 'datetime',
			'Nodes.created' => 'datetime',
			'created' => 'datetime',
			'Nodes__created_by' => 'integer',
			'Nodes.created_by' => 'integer',
			'created_by' => 'integer',
			'Taxonomies__id' => 'integer',
			'Taxonomies.id' => 'integer',
			'Taxonomies__parent_id' => 'integer',
			'Taxonomies.parent_id' => 'integer',
			'Taxonomies__term_id' => 'integer',
			'Taxonomies.term_id' => 'integer',
			'term_id' => 'integer',
			'Taxonomies__vocabulary_id' => 'integer',
			'Taxonomies.vocabulary_id' => 'integer',
			'vocabulary_id' => 'integer',
			'Taxonomies__lft' => 'integer',
			'Taxonomies.lft' => 'integer',
			'Taxonomies__rght' => 'integer',
			'Taxonomies.rght' => 'integer',
			'Terms__id' => 'integer',
			'Terms.id' => 'integer',
			'Terms__title' => 'string',
			'Terms.title' => 'string',
			'Terms__slug' => 'string',
			'Terms.slug' => 'string',
			'Terms__description' => 'text',
			'Terms.description' => 'text',
			'description' => 'text',
			'Terms__updated' => 'datetime',
			'Terms.updated' => 'datetime',
			'Terms__updated_by' => 'integer',
			'Terms.updated_by' => 'integer',
			'Terms__created' => 'datetime',
			'Terms.created' => 'datetime',
			'Terms__created_by' => 'integer',
			'Terms.created_by' => 'integer',
			'Vocabularies__id' => 'integer',
			'Vocabularies.id' => 'integer',
			'Vocabularies__title' => 'string',
			'Vocabularies.title' => 'string',
			'Vocabularies__alias' => 'string',
			'Vocabularies.alias' => 'string',
			'alias' => 'string',
			'Vocabularies__description' => 'text',
			'Vocabularies.description' => 'text',
			'Vocabularies__required' => 'boolean',
			'Vocabularies.required' => 'boolean',
			'required' => 'boolean',
			'Vocabularies__multiple' => 'boolean',
			'Vocabularies.multiple' => 'boolean',
			'multiple' => 'boolean',
			'Vocabularies__tags' => 'boolean',
			'Vocabularies.tags' => 'boolean',
			'tags' => 'boolean',
			'Vocabularies__plugin' => 'string',
			'Vocabularies.plugin' => 'string',
			'plugin' => 'string',
			'Vocabularies__weight' => 'integer',
			'Vocabularies.weight' => 'integer',
			'weight' => 'integer',
			'Vocabularies__updated' => 'datetime',
			'Vocabularies.updated' => 'datetime',
			'Vocabularies__updated_by' => 'integer',
			'Vocabularies.updated_by' => 'integer',
			'Vocabularies__created' => 'datetime',
			'Vocabularies.created' => 'datetime',
			'Vocabularies__created_by' => 'integer',
			'Vocabularies.created_by' => 'integer',
			'Users__id' => 'integer',
			'Users.id' => 'integer',
			'Users__role_id' => 'integer',
			'Users.role_id' => 'integer',
			'role_id' => 'integer',
			'Users__username' => 'string',
			'Users.username' => 'string',
			'username' => 'string',
			'Users__password' => 'string',
			'Users.password' => 'string',
			'password' => 'string',
			'Users__name' => 'string',
			'Users.name' => 'string',
			'name' => 'string',
			'Users__email' => 'string',
			'Users.email' => 'string',
			'email' => 'string',
			'Users__website' => 'string',
			'Users.website' => 'string',
			'website' => 'string',
			'Users__activation_key' => 'string',
			'Users.activation_key' => 'string',
			'activation_key' => 'string',
			'Users__image' => 'string',
			'Users.image' => 'string',
			'image' => 'string',
			'Users__bio' => 'text',
			'Users.bio' => 'text',
			'bio' => 'text',
			'Users__status' => 'boolean',
			'Users.status' => 'boolean',
			'Users__updated' => 'datetime',
			'Users.updated' => 'datetime',
			'Users__updated_by' => 'integer',
			'Users.updated_by' => 'integer',
			'Users__created' => 'datetime',
			'Users.created' => 'datetime',
			'Users__timezone' => 'string',
			'Users.timezone' => 'string',
			'timezone' => 'string',
			'Users__created_by' => 'integer',
			'Users.created_by' => 'integer',
			'Types__id' => 'integer',
			'Types.id' => 'integer',
			'Types__title' => 'string',
			'Types.title' => 'string',
			'Types__alias' => 'string',
			'Types.alias' => 'string',
			'Types__description' => 'text',
			'Types.description' => 'text',
			'Types__format_show_author' => 'boolean',
			'Types.format_show_author' => 'boolean',
			'format_show_author' => 'boolean',
			'Types__format_show_date' => 'boolean',
			'Types.format_show_date' => 'boolean',
			'format_show_date' => 'boolean',
			'Types__format_use_wysiwyg' => 'boolean',
			'Types.format_use_wysiwyg' => 'boolean',
			'format_use_wysiwyg' => 'boolean',
			'Types__comment_status' => 'integer',
			'Types.comment_status' => 'integer',
			'Types__comment_approve' => 'boolean',
			'Types.comment_approve' => 'boolean',
			'comment_approve' => 'boolean',
			'Types__comment_spam_protection' => 'boolean',
			'Types.comment_spam_protection' => 'boolean',
			'comment_spam_protection' => 'boolean',
			'Types__comment_captcha' => 'boolean',
			'Types.comment_captcha' => 'boolean',
			'comment_captcha' => 'boolean',
			'Types__params' => 'text',
			'Types.params' => 'text',
			'params' => 'text',
			'Types__plugin' => 'string',
			'Types.plugin' => 'string',
			'Types__updated' => 'datetime',
			'Types.updated' => 'datetime',
			'Types__updated_by' => 'integer',
			'Types.updated_by' => 'integer',
			'Types__created' => 'datetime',
			'Types.created' => 'datetime',
			'Types__created_by' => 'integer',
			'Types.created_by' => 'integer',
			'Meta__id' => 'integer',
			'Meta.id' => 'integer',
			'Meta__model' => 'string',
			'Meta.model' => 'string',
			'model' => 'string',
			'Meta__foreign_key' => 'integer',
			'Meta.foreign_key' => 'integer',
			'foreign_key' => 'integer',
			'Meta__key' => 'string',
			'Meta.key' => 'string',
			'key' => 'string',
			'Meta__value' => 'text',
			'Meta.value' => 'text',
			'value' => 'text',
			'Meta__weight' => 'integer',
			'Meta.weight' => 'integer',
			'Meta__created' => 'datetime',
			'Meta.created' => 'datetime',
			'Meta__created_by' => 'integer',
			'Meta.created_by' => 'integer',
			'Meta__updated' => 'datetime',
			'Meta.updated' => 'datetime',
			'Meta__updated_by' => 'integer',
			'Meta.updated_by' => 'integer'
		],
		'decorators' => (int) 0,
		'executed' => false,
		'hydrate' => true,
		'buffered' => true,
		'formatters' => (int) 2,
		'mapReducers' => (int) 0,
		'contain' => [
			'Taxonomies' => [
				'Terms' => [],
				'Vocabularies' => []
			],
			'Users' => [],
			'Types' => [],
			'Meta' => []
		],
		'matching' => [],
		'extraOptions' => [
			'config' => 'croogo_nodes',
			'prefix' => 'nodes_recent_posts',
			'roleId' => (int) 1
		],
		'repository' => object(Croogo\Nodes\Model\Table\NodesTable) {

			'registryAlias' => 'Croogo/Nodes.Nodes',
			'table' => 'nodes',
			'alias' => 'Nodes',
			'entityClass' => 'Croogo\Nodes\Model\Entity\Node',
			'associations' => [
				(int) 0 => 'taxonomies',
				(int) 1 => 'meta',
				(int) 2 => 'trackablecreator',
				(int) 3 => 'trackableupdater',
				(int) 4 => 'users',
				(int) 5 => 'parent',
				(int) 6 => 'types',
				(int) 7 => 'modeltaxonomies'
			],
			'behaviors' => [
				(int) 0 => 'Taxonomizable',
				(int) 1 => 'Meta',
				(int) 2 => 'Tree',
				(int) 3 => 'BulkProcess',
				(int) 4 => 'Publishable',
				(int) 5 => 'Url',
				(int) 6 => 'Trackable',
				(int) 7 => 'Visibility',
				(int) 8 => 'Cached',
				(int) 9 => 'Search',
				(int) 10 => 'Timestamp'
			],
			'defaultConnection' => 'default',
			'connectionName' => 'default'
		
		}
	
	}
]

**Comment by rchavik** [comment]
Just do a loop on it, eg:

```php
foreach ($entity in $nodesForLayout['recent_posts']):
   debug($entity);
endforeach;
```

**Comment by rchavik** [comment]
Additional info: https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#using-finders-to-load-data

**Comment by slightlychilled** [comment]
Hi there. As mentioned in my issue post, that does not work as we do not get the data. This is still an issue.

**Comment by slightlychilled** [comment]
The output from DEBUG does NOT contain the data selected. I think there is an issue with populating the $nodesForLayout variable with the data selected in the block. Can we re-open this issue, as your stated solution does not work.

**Comment by rchavik** [comment]
Did you dump $entity or $nodesForLayout?

**Comment by rchavik** [comment]
Also, you can turn on debug mode and use DebugKit's variable panel to inspect its content:

![image](https://user-images.githubusercontent.com/39490/60697437-7ace1800-9f14-11e9-9eb5-073d90d590bb.png)
