### ISSUE TITLE
croogo v3.0.5 Code Execution Vulnerability in "Theme" Settings

### ISSUE THREAD

**Issue by Invi0sible** [croogo/croogo#899]
1. login as admin
2.Settings--Theme, upload evil php file via /croogo/admin/settings/settings/prefix/Theme

![image](https://user-images.githubusercontent.com/33925178/63316583-f4458c80-c341-11e9-8bdf-e8f5553d62fe.png)
![image](https://user-images.githubusercontent.com/33925178/63316686-4d152500-c342-11e9-8543-f31a2bcc07a0.png)

3.visit evil php via http://10.211.55.8/croogo/uploads/evil.php
![image](https://user-images.githubusercontent.com/33925178/63316655-2fe05680-c342-11e9-9147-9a9c95c224d0.png)

**Comment by Invi0sible** [comment]
Hello,Is this not a valid vulnerability?

**Comment by rchavik** [comment]
Yes.. it's fixed in 4.0 branch
