### ISSUE TITLE
Node View Fallback

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#901]
Unable to use node specific view files in theme, fallback does not seem to work anymore when using a view file. e.g.:

plugins/Live/src/Template/Nodes/view_5.ctp

**Comment by rchavik** [comment]
Try using the following path `plugins/Live/src/Template/Nodes/view/node_5.ctp` or `plugins/Live/src/Template/Nodes/view/hello_world.ctp`

**Comment by slightlychilled** [comment]
Thanks for that. It now works.
