### ISSUE TITLE
Adding links to menus is not working

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#902]
When adding a link to a menu, the link chooser is causing major issues when it auto-formats the link. E.G.:

When you want to use a link to an anchor on a home page /#contact you end up with the following link:

/%2f#contact

This is obviously wrong, and the auto-formatting should not convert the link in this way.

**Comment by slightlychilled** [comment]
Also, on checking the database there are further errors. Linking to the home page:

should not be stored as: plugin:Croogo%2fNodes/controller:Nodes/action:promoted

should be stored as: plugin:Croogo/Nodes/controller:Nodes/action:promoted

**Comment by rchavik** [comment]
> should not be stored as: plugin:Croogo%2fNodes/controller:Nodes/action:promoted

This is correct. the %2f is html escaped from `/`. Otherwise see below:

> should be stored as: plugin:Croogo/Nodes/controller:Nodes/action:promoted

Since we use `/` as delimiter, the value of plugin would be `Croogo`.  It's supposed to be `Croogo/Nodes`

**Comment by slightlychilled** [comment]
So, how should we enter /#contact as a link?

**Comment by rchavik** [comment]
Try leaving out the `/`?

**Comment by slightlychilled** [comment]
Unfortunately, that won't work. If I am on a page within the site, and I want to go back to an anchor tag on the home page I would need /#anchor as the relative link. If I leave out the / I would go to an anchor tag on the same page...

**Comment by rchavik** [comment]
not sure about this, but try with `plugin:Croogo/Nodes controller:Nodes action:promoted #anchor`

**Comment by slightlychilled** [comment]
Nope, now we get http://testsite/promoted/%23anchortag

**Comment by slightlychilled** [comment]
It needs looking as, as anchor tags are common use for navigation.

**Comment by rchavik** [comment]
If you're developing for a new site, do you mind helping me by using 4.x instead?

I don't have the bandwith to work on 3.x at the moment.

**Comment by slightlychilled** [comment]
Sure can. Is 4 in a stable state?

**Comment by slightlychilled** [comment]
Also, is there a way I can contact you directly, as I am working through the code, and as I find issues (and hopefully fixes) I can send them through to you. I'd like to be more involved with this project.

**Comment by rchavik** [comment]
4.x is still alpha, but I'm currently working on this.  Issues would be more likely be addressed on this branch.

You can try slack: https://cakesf.slack.com/ or https://gitter.im/croogo/croogo (you can use github login).

**Comment by rchavik** [comment]
Should be working now in 4.x
