### ISSUE TITLE
Adding Content - Created Date is missing from form

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#903]
When adding content there used to be a 'created date' input field. However, there is now only a 'Publish On' and an 'Un-Publish On' field.

Considering that the default ordering of content is based on created date, the 'Created date' field must be available for editing to assist in controlling the order of content. Please add back in the 'Created Date' input field when adding and editing content.

**Comment by slightlychilled** [comment]
To fix this please change:

vendor/croogo/croogo/Core/src/Template/Element/admin/publishable.ctp

to the following:

<?php
/**
 * @var \Croogo\Core\View\CroogoView $this
 */
use Croogo\Core\Status;

echo $this->Form->input('status', [
    'label' => __d('croogo', 'Status'),
    'class' => 'c-select',
    'default' => Status::UNPUBLISHED,
    'options' => $this->Croogo->statuses(),
]);

echo $this->Html->div('input', $this->Form->input('created', [
        'label' => __d('croogo', 'Created'),
        'empty' => true,
    ]));

echo $this->Html->div('input-daterange', $this->Form->input('publish_start', [
        'label' => __d('croogo', 'Publish on'),
        'empty' => true,
    ]) . $this->Form->input('publish_end', [
        'label' => __d('croogo', 'Un-publish on'),
        'empty' => true,
    ]));

**Comment by slightlychilled** [comment]
to be clear: adding in

echo $this->Html->div('input', $this->Form->input('created', [
        'label' => __d('croogo', 'Created'),
        'empty' => true,
    ]));

**Comment by slightlychilled** [comment]
OK, so adding this in breaks other areas such as blocks, links etc. Any suggestions on a solution?

**Comment by slightlychilled** [comment]
Found my own solution:

if($this->request->params['controller'] == 'Nodes') {
	echo $this->Html->div('input', $this->Form->input('created', [
			'label' => __d('croogo', 'Created'),
			'empty' => true,
		]));
}

**Comment by rchavik** [comment]
I'm thinking of change the behaviour so that ordering always uses publish_start, so some change will be need to auto fill publish_start, and queries need adjustment too

**Comment by rchavik** [comment]
Closing since PR is open.
