### ISSUE TITLE
Out put individual variables from array

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#905]
In previous versions of Croogo you could output a variable from an array using echo $nodes['2']['Node']['title'];

This no longer works?

What should I use instead?

**Comment by rchavik** [comment]
try doing `debug($nodes[2])` first. 

IIRC, Its content would be a `Node` entity. Then access it via `$nodes[2]->title`

**Comment by slightlychilled** [comment]
Nope, that does not work either....

**Comment by slightlychilled** [comment]
I get:

/plugins/Live/src/Template/Nodes/promoted.ctp (line 11)
object(Cake\Datasource\ResultSetDecorator) {

	'count' => (int) 4

}

**Comment by slightlychilled** [comment]
When I use:

foreach ($nodes as $node){
				debug($node);
			}

I get the full output:

/plugins/Live/src/Template/Nodes/promoted.ctp (line 11)
object(Croogo\Nodes\Model\Entity\Node) {

	'id' => (int) 1,
	'parent_id' => null,
	'user_id' => (int) 1,
	'title' => 'Home Page Content',
	'slug' => 'home-page-content',
	'body' => '<p>Body Text</p>',
	'excerpt' => '',
	'status' => (int) 1,
	'mime_type' => null,
	'comment_status' => (int) 1,
	'comment_count' => (int) 0,
	'promote' => true,
	'path' => '/page/home-page-content',
	'terms' => null,
	'sticky' => false,
	'lft' => (int) 1,
	'rght' => (int) 2,
	'visibility_roles' => null,
	'type' => 'page',
	'publish_start' => null,
	'publish_end' => null,
	'updated' => object(Cake\I18n\FrozenTime) {

		'time' => '2019-08-29T05:27:01+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'updated_by' => (int) 1,
	'created' => object(Cake\I18n\FrozenTime) {

		'time' => '2019-10-03T04:07:00+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'created_by' => (int) 1,
	'meta' => [],
	'multiattach' => [],
	'node_type' => object(Cake\ORM\Entity) {

		'id' => (int) 1,
		'title' => 'Page',
		'alias' => 'page',
		'description' => 'Default pages of content for your website.',
		'format_show_author' => false,
		'format_show_date' => false,
		'format_use_wysiwyg' => true,
		'comment_status' => (int) 0,
		'comment_approve' => true,
		'comment_spam_protection' => false,
		'comment_captcha' => false,
		'params' => 'routes=true',
		'plugin' => null,
		'updated' => object(Cake\I18n\FrozenTime) {

			'time' => '2019-06-03T06:00:54+00:00',
			'timezone' => 'UTC',
			'fixedNowTime' => false
		
		},
		'updated_by' => (int) 1,
		'created' => object(Cake\I18n\FrozenTime) {

			'time' => '2019-06-03T06:00:12+00:00',
			'timezone' => 'UTC',
			'fixedNowTime' => false
		
		},
		'created_by' => (int) 1,
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Croogo/Nodes.Types'
	
	},
	'user' => object(Croogo\Users\Model\Entity\User) {

		'id' => (int) 1,
		'role_id' => (int) 1,
		'username' => 'simon',
		'password' => '$2y$10$Yjk5EEAJvlna4Lm2RyXhhuYTFzxdigRXRZ0PDEyUqFqTAEF1NxSoG',
		'name' => 'simon',
		'email' => '',
		'website' => null,
		'activation_key' => '45387f68ce7a2bbeda2643959c98f005',
		'image' => null,
		'bio' => null,
		'status' => true,
		'updated' => object(Cake\I18n\FrozenTime) {

			'time' => '2019-06-01T06:36:57+00:00',
			'timezone' => 'UTC',
			'fixedNowTime' => false
		
		},
		'updated_by' => null,
		'created' => object(Cake\I18n\FrozenTime) {

			'time' => '2019-06-01T06:36:57+00:00',
			'timezone' => 'UTC',
			'fixedNowTime' => false
		
		},
		'timezone' => 'UTC',
		'created_by' => null,
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Croogo/Users.Users'
	
	},
	'taxonomies' => [],
	'custom_fields' => [],
	'url' => object(Croogo\Core\Link) {
		plugin => 'Croogo/Nodes'
		controller => 'Nodes'
		action => 'view'
		type => 'page'
		slug => 'home-page-content'
	},
	'[new]' => false,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'custom_fields' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Croogo/Nodes.Nodes'

}

**Comment by rchavik** [comment]
My mistake, Query object cannot be accessed via array. You need to iterate it first, like using foreach.

You can manually call all():

`$myNodes = $nodes->all(); debug($myNodes[2]); `

**Comment by slightlychilled** [comment]
That does not work either ;(

**Comment by rchavik** [comment]
Should be resolved by now. If still not resolved, please ask in channel.
