### ISSUE TITLE
PHP 7.3 pcre upgrades

### ISSUE THREAD

**Issue by miketallroth** [croogo/croogo#922]
PHP 7.3 bundles a newer version of pcre as compared to PHP 7.2 (7.3 => pcre2 v10.32, 7.2 => pcre v8.43). This change affects how the character range character ('-') is parsed, and at least in some cases, it is now required to be escaped whereas in previous versions, it was not.
https://www.php.net/manual/en/pcre.installation.php

The UsersTable.php file is one case where this version difference causes an error. The validation for the name field being alphaNumeric is `/^[\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}-_\[\]\(\) ]+$/`. Apparently, the dash near the end of the regex is ambiguous in the new pcre2, so it is causing an error on installation. Its a PHP warning, but it also causes a null string, which then prevents the admin user from being created. Note the two outputs below from a 7.2.24 environment and a 7.3.11 environment.

Fortunately, the fix is simply escaping the offending range character. I'll try to do a search through the entire library to test for any other offending regex strings.

```
miket@hp840-3:~/workspace/sqlite $ cat test.php
<?php

$rule1 = '/^[\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}-_\[\]\(\) ]+$/mu';
$rule2 = '/^[\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}\-_\[\]\(\) ]+$/mu';

echo "testing rule1\n";
if (preg_match($rule1, 'test string')) {
	echo "rule1 match\n";
}

echo "testing rule2\n";
if (preg_match($rule2, 'test string')) {
	echo "rule2 match\n";
}
```

```
miket@hp840-3:~/workspace/sqlite $ php --version
PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
miket@hp840-3:~/workspace/sqlite $ php -f test.php 
testing rule1
rule1 match
testing rule2
rule2 match

```

```
root@5cf9c2ba953b:/var/www/html# php --version
PHP 7.3.11 (cli) (built: Oct 25 2019 02:28:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
root@5cf9c2ba953b:/var/www/html# php -f test.php 
testing rule1

Warning: preg_match(): Compilation failed: invalid range in character class at offset 38 in /var/www/html/test.php on line 7
testing rule2
rule2 match

```

**Comment by rchavik** [comment]
Closing since PR is merged
