### ISSUE TITLE
LanguagesSeed.php still causing issues

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#926]
On install, the process fails due to issue with LanguagesSeed.php found in:

/vendor/croogo/croogo/Settings/config/Seeds

deletion of the file allows the installation to continue

**Comment by rchavik** [comment]
Please provide the error/stacktrace here.

**Comment by slightlychilled** [comment]
to replicate the issue just use the download file and go through an installation.

**Comment by rchavik** [comment]
I asked because it's not happening to me.

**Comment by rchavik** [comment]
Closing since I can't repro.
