### ISSUE TITLE
Install new copy Croogo 4[permission files]

### ISSUE THREAD

**Issue by Vadimushka** [croogo/croogo#938]
1) run command `composer create-project croogo/app croogo4`
2) download croogo4 and other libraries
3) open site to browser
![2019-11-26_10-59](https://user-images.githubusercontent.com/6237552/69609996-e20f7480-103b-11ea-9b63-0871dcd4b46d.png)
4) cat error.log from (/var/log/apache2/) (down)
`[Tue Nov 26 10:46:53.103969 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP Warning:  file_put_contents(/home/croogo/croogo4/logs/error.log) [<a href='https://secure.php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /home/croogo/croogo4/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 132
[Tue Nov 26 10:46:53.104018 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP Stack trace:
[Tue Nov 26 10:46:53.104031 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   1. {main}() /home/croogo/croogo4/webroot/index.php:0
[Tue Nov 26 10:46:53.104040 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   2. Cake\\Http\\Server->run() /home/croogo/croogo4/webroot/index.php:40
[Tue Nov 26 10:46:53.104048 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   3. Cake\\Http\\Server->bootstrap() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Http/Server.php:81
[Tue Nov 26 10:46:53.104057 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   4. App\\Application->pluginBootstrap() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Http/Server.php:123
[Tue Nov 26 10:46:53.104067 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   5. Croogo\\Core\\Plugin->bootstrap() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Http/BaseApplication.php:160
[Tue Nov 26 10:46:53.104077 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   6. Croogo\\Core\\PluginManager::setup() /home/croogo/croogo4/vendor/croogo/croogo/Core/src/Plugin.php:18
[Tue Nov 26 10:46:53.104086 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   7. Cake\\Core\\Configure::load() /home/croogo/croogo4/vendor/croogo/croogo/Core/src/PluginManager.php:1298
[Tue Nov 26 10:46:53.104095 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   8. Croogo\\Settings\\Configure\\Engine\\DatabaseConfig->read() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Core/Configure.php:342
[Tue Nov 26 10:46:53.104102 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP   9. Cake\\Cache\\Cache::remember() /home/croogo/croogo4/vendor/croogo/croogo/Settings/src/Configure/Engine/DatabaseConfig.php:50
[Tue Nov 26 10:46:53.104108 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  10. Cake\\Cache\\Cache::read() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Cache.php:654
[Tue Nov 26 10:46:53.104113 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  11. Cake\\Cache\\Cache::engine() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Cache.php:378
[Tue Nov 26 10:46:53.104119 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  12. Cake\\Cache\\Cache::_buildEngine() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Cache.php:236
[Tue Nov 26 10:46:53.104124 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  13. Cake\\Cache\\CacheRegistry->load() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Cache.php:174
[Tue Nov 26 10:46:53.104130 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  14. Cake\\Cache\\CacheRegistry->_create() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php:96
[Tue Nov 26 10:46:53.104135 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  15. Cake\\Cache\\Engine\\FileEngine->init() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/CacheRegistry.php:89
[Tue Nov 26 10:46:53.104141 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  16. Cake\\Cache\\Engine\\FileEngine->_active() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php:105
[Tue Nov 26 10:46:53.104146 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  17. trigger_error() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php:445
[Tue Nov 26 10:46:53.104151 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  18. Cake\\Error\\ErrorHandler->handleError() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php:445
[Tue Nov 26 10:46:53.104157 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  19. Cake\\Error\\ErrorHandler->_logError() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php:158
[Tue Nov 26 10:46:53.104169 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  20. Cake\\Log\\Log::write() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php:296
[Tue Nov 26 10:46:53.104174 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  21. Cake\\Log\\Engine\\FileLog->log() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Log/Log.php:383
[Tue Nov 26 10:46:53.104180 2019] [php7:notice] [pid 7059] [client 127.0.0.1:60688] PHP  22. file_put_contents() /home/croogo/croogo4/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php:132`

5) not file /logs/error.log
6) i'm create this file
7) in this file
`2019-11-26 07:51:06 Warning: Warning (512): /home/croogo/croogo4/tmp/cache/queries/ is not writable in [/home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 445]`
`2019-11-26 07:51:06 Warning: Warning (512): /home/croogo/croogo4/tmp/cache/persistent/ is not writable in [/home/croogo/croogo4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 445]`

**Comment by rchavik** [comment]
This looks like permission issue on the `tmp` and `logs` directory.

Please refer to https://book.cakephp.org/3/en/installation.html#permissions to set the correct permissions.

If you just want to test locally, you can try [using the builtin webserver](https://book.cakephp.org/3/en/installation.html#development-server)

**Comment by rchavik** [comment]
Closing. Please ask in chat if not resolved.
