### ISSUE TITLE
MySQL Error while activating the example

### ISSUE THREAD

**Issue by amjo** [croogo/croogo#945]
i often check for updates on croogo versions. out of curiosity i decided to deploy Croogo 4.0.2.

while checking around and activating Examples plugin i got the following MySQL error:

```
SQLSTATE[HY000]: General error: 1364 Field 'created_by' doesn't have a default value 
SQL Query: INSERT INTO links (menu_id, title, class, link, status, lft, rght, visibility_roles, created, modified) VALUES (:c0, :c1, :c2, :c3, :c4, :c5, :c6, :c7, :c8, :c9) 
```

This isn't a high importance bug, i just thought of reporting it.

Windows 10, WAMP 3.1.3, PHP 7.2.4, MySQL 5.7.21
Used Composer for installation

**Comment by rchavik** [comment]
Thanks for the report. Will fix for next release
