### ISSUE TITLE
Croogo Installation issue

### ISSUE THREAD

**Issue by cibyjohn** [croogo/croogo#946]
while adding croogo in the existing project in a separate folder and accessing the url is not working.
while checking the error log showing as 
Error: Plugin not found during bootstrap: Up2rock

can you please help me to resolve this issue.
![Capture](https://user-images.githubusercontent.com/59648618/72974724-85d78f80-3df5-11ea-8aac-3a822946d0ad.PNG)

**Comment by rchavik** [comment]
This is not a bug per se. Please ask https://gitter.im/croogo/croogo or in irc
