### ISSUE TITLE
Plugin Routes Error

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#948]
In croogo3 in the plugin/config/bootstrap.php we used the following to load route
Croogo::hookRoutes('Plugin');

However, this is now producing the error "Call to undefined method Croogo\Core\Croogo::hookRoutes()"
How do I now load plugin specific routes?

**Comment by rchavik** [comment]
You don't need to call Croogo::hookRoutes().  Just create `config/routes.php` and Croogo will automatically load it.
