### ISSUE TITLE
Comments form URL

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#952]
Comments form is generating the following UL:

/comments/comments/add/Croogo%252FNodes.Nodes/1

**Comment by rchavik** [comment]
This is intended.  We needed to escape `\` character.

**Comment by slightlychilled** [comment]
So, howdy we get the form to work with that URL?

**Comment by rchavik** [comment]
It should already work.  Which part is failing for you?

**Comment by slightlychilled** [comment]
The URL structure /comments/comments/add/Croogo%252FNodes.Nodes/1

**Comment by rchavik** [comment]
i need more info.  browsing to that url works for me.

it presents me with the following screen: 
![image](https://user-images.githubusercontent.com/39490/74329230-f9036e80-4dc1-11ea-93a1-28afa4175961.png)

And submitting the form also works as expected.

**Comment by slightlychilled** [comment]
the form action is /comments/comments/add/Croogo%252FNodes.Nodes/1

If you try submitting a comment you will get a page not found.

**Comment by rchavik** [comment]
> And submitting the form also works as expected.

There must be something else. Is there anything on the logs? I can't guess what is wrong without more info.

**Comment by rchavik** [comment]
Found root cause after discussions: https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes

Will try to convert to querystring
