### ISSUE TITLE
CKEditor issue on contact add/edit

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#968]
When adding a new contact, or trying to edit a contact the creditor is not shown and the following error is shown when inspecting the page:

Error: The specified element mode is not supported on element: "body".

on ckeditor.js:274:506

**Comment by slightlychilled** [comment]
Resolution:

update Contacts/config/bootstrap.php:

Change both entries of
'elements' => 'body',
to
'elements' => '#body',

**Comment by rchavik** [comment]
Care to submit a PR?
