### ISSUE TITLE
Wysiwyg editor for Excerpt field

### ISSUE THREAD

**Issue by miketallroth** [croogo/croogo#969]
I wanted to share a few more thoughts on the Excerpt field and offer a slightly different way of dealing with it. I can do the work in a PR, but wanted to talk it through before committing to anything.

1. I found the NodesHelper::excerpt() and the StringConverter::firstPara() methods which make sense to me. However, this is inconsistent in the sense that if it uses the body field as it's source, it will contain markup (at least the paragraph tags), but if it uses the field itself, it contains no markup (because of the lack of the wysiwyg editor). Instead if we had markup in the Excerpt field, then the two uses here would be consistent.
2. If Excerpt does not use markup, then it serves exactly the same purpose as the meta_description field, hence there is no need to have both.

Therefore, I suggest we include the wysiwyg editor for the Excerpt field, and treat them as follows;
   * Body -> full article for single article view or for full list view
   * Excerpt -> article extract (automatic or edited/custom) for highlight-only list view
      * this is as it is being used now in promoted, search, term and index
   * Description -> meta data only (automatic or edited/custom) no rendering

These suggestions would require only two things;
  1. Add the configuration to use Wysiwyg on the Excerpt field
  2. Add a call to strip_tags to ensure meta_description is stripped of markup in case it is being populated from either the excerpt or body fields.

Anyone have thoughts about this?

**Comment by rchavik** [comment]
> I found the NodesHelper::excerpt() and the StringConverter::firstPara() methods which make sense to me. However, this is inconsistent in the sense that if it uses the body field as it's source, it will contain markup (at least the paragraph tags)

IIRC, the intention for it is to **not** contain any tags. If existing code results in `<p>`, then it is incorrect.

> If Excerpt does not use markup, then it serves exactly the same purpose as the meta_description field, hence there is no need to have both.

Yes, this is duplicate functionality.  Primarily for backward compatibility or others.

> These suggestions would require only two things;
>
>    Add the configuration to use Wysiwyg on the Excerpt field
>    Add a call to strip_tags to ensure meta_description is stripped of markup in
case it is being populated from either the excerpt or body fields.
>
> Anyone have thoughts about this?

I think this makes sense.  So, one can use the excerpt field with tags for whatever purpose they want.  And strip_tags to populate `meta description` content if SEO meta_description field is empty.
