### ISSUE TITLE
Writing.wysiwyg not used?

### ISSUE THREAD

**Issue by miketallroth** [croogo/croogo#972]
It appears the Writing.wysiwyg setting is not used in Croogo anymore.

If I'm understanding this correctly, it was used to enable / disable the wysiwyg editor in the Node editors, but that seems to have been replaced by the type-specific format_use_wysiwyg field instead. Does it need to be kept around for developers to migrate existing production code up to current Croogo, or can I remove it?

I can produce the PR to remove this and the related Setting > Writing menu item, just looking for a confirmation that my assumptions are correct.

**Comment by rchavik** [comment]
Lets remove it. Agree with type specific config.

**Comment by miketallroth** [comment]
Resolved by commit 9c7862a. I kind of botched that commit (didn't use good style of branch and merge), but the end result is what I wanted. Let me know if you want me to fix anything.

**Comment by rchavik** [comment]
Thanks for taking care of this
