### ISSUE TITLE
NodesController -> terms pagination show only first block

### ISSUE THREAD

**Issue by robivin** [croogo/croogo#975]
You need change this line
$this->paginate['page'] = $this->getRequest()->getParam('page') ?: 1;
to this
$this->paginate['page'] = $this->getRequest()->getQuery('page') ?: 1;

I tried to apply to contribute to the project but I failed.

Bye  

Robert

**Comment by rchavik** [comment]
> I tried to apply to contribute to the project but I failed.

Can you create a pull request? You can use github web interface to do this.

**Comment by robivin** [comment]
OK

**Comment by rchavik** [comment]
Thanks.

Closed by 0e33d472ea89e456c82cfd31410ca8be08c430a1 (squashed from #977)
