### ISSUE TITLE
Run IdeHelper

### ISSUE THREAD

**Issue by dereuromark** [croogo/croogo#986]
You can run IdeHelper per cake4 module/plugin of yours, e.g.:

    bin/cake annotate all -p Croogo/Core

It will fix a lot of classes and adds missing annotations for IDE clickability and PHPStan understanding, e.g.
```diff
+ * @property \Cake\View\Helper\FormHelper $Form
+ * @property \Cake\View\Helper\HtmlHelper $Html
+ * @property \Cake\View\Helper\UrlHelper $Url
+ * @property \Croogo\Core\View\Helper\LayoutHelper $Layout
+ * @property \Croogo\Core\View\Helper\ThemeHelper $Theme
+ * @property \Croogo\Menus\View\Helper\MenusHelper $Menus
+ * @property \Croogo\Acl\View\Helper\AclHelper $Acl
  */
 class CroogoHelper extends Helper
```

It also finds a few other issues:

> Notice: Deprecated (16384): RssHelper is deprecated and will be removed in 4.0.0

This you could replace with e.g. https://github.com/dereuromark/cakephp-feed

You just might want to double check the template annotations, as they might not be what you need.

**Comment by rchavik** [comment]
Yes, thanks. Will do this soon

**Comment by rchavik** [comment]
Done in https://github.com/croogo/croogo/commit/56bcf30fbcdbb6e824d08b3af9b3ffb590f05034
